#config_version=6

 
mode:
  start_events: start_mode_skillshot
  stop_events: stop_mode_skillshot
  priority: 1000


event_player:
  #mode_skillshot_started: 
   # - play_skillshot_start_slide
   # - remove_skillshot_start_slide|2s
   # - play_main_screen_slide|2.1s
  skillshot_lit_hit: stop_mode_skillshot|3s
  playfield_active: stop_mode_skillshot|1s
  skillshot_drop_1_off_hit: stop_mode_skillshot
  skillshot_drop_2_off_hit: stop_mode_skillshot
  skillshot_drop_3_off_hit: stop_mode_skillshot

shot_groups:
  skillshot:
    shots:
      - skillshot_drop_1
      - skillshot_drop_2
      - skillshot_drop_3
    reset_events: mode_skillshot_starting


random_event_player:
  mode_skillshot_started:
    events:
      - advance_skillshot_1
      - advance_skillshot_2
      - advance_skillshot_3


shots:
  skillshot_drop_1:
    switch: s_3_bank_drop_target_1
    advance_events: advance_skillshot_1
    profile: skillshot_profile
    show_tokens:
      lights: skill_shot_1, skill_shot_round
  skillshot_drop_2:
    switch: s_3_bank_drop_target_2
    advance_events: advance_skillshot_2
    profile: skillshot_profile
    show_tokens:
      lights: skill_shot_2, skill_shot_round
  skillshot_drop_3:
    switch: s_3_bank_drop_target_3
    advance_events: advance_skillshot_3
    profile: skillshot_profile
    show_tokens:
      lights: skill_shot_3, skill_shot_round

shot_profiles:
  skillshot_profile:
    advance_on_hit: false
    states:
      - name: off
        show: off
      #- name: on
      #  show: on
      - name: lit
        show: flash




slides:
  skillshot_start:
    widgets:
      - type: text
        text: Hit the flashing skillshot
        color: gold
        font_size: 120
        font_name: CarnivaleeFreakshow-DLrm
      - type: image
        image: bar_screen
        scale: 1



  skillshot_hit:
    widgets:
      - type: text
        text: YOU HIT THE SKILL SHOT!
        color: gold
        font_size: 120
        font_name: CarnivaleeFreakshow-DLrm
        y: 75%
      - type: text
        text: 200,000 points
        font_name: CarnivaleeFreakshow-DLrm
        y: 25%
        font_size: 120
      - type: image
        image: bar_screen
        scale: 1
        
      

slide_player:

  skillshot_drop_1_lit_hit: skillshot_hit
  skillshot_drop_2_lit_hit: skillshot_hit
  skillshot_drop_3_lit_hit: skillshot_hit

sounds:
  skillshot:
    file: skillshot.wav
    track: voice
    volume: 0.9
    priority: 100



sound_player:
  skillshot_drop_1_lit_hit:
    skillshot:
      action: play
      loops: 0
  skillshot_drop_2_lit_hit:
    skillshot:
      action: play
      loops: 0
  skillshot_drop_3_lit_hit:
    skillshot:
      action: play
      loops: 0




variable_player:
  skillshot_drop_1_lit_hit:
    score: 200000
  skillshot_drop_2_lit_hit:
    score: 200000
  skillshot_drop_3_lit_hit:
    score: 200000






  