#config_version=6

#skillshot_with_auto_rotate
 
mode:
  start_events: start_mode_skillshot
  stop_events: stop_mode_skillshot
  priority: 1000


event_player:
  timer_skillshot_rotate_stopped:
    # Whichever skillshot is on when rotation stops, advance to lit (flashing)
    - advance_skillshot_1{device.shots.skillshot_drop_1.state==1}
    - advance_skillshot_2{device.shots.skillshot_drop_2.state==1}
    - advance_skillshot_3{device.shots.skillshot_drop_3.state==1}
  skillshot_hit: stop_mode_skillshot
  playfield_active: stop_mode_skillshot|3s

shot_groups:
  skillshot:
    shots:
      - skillshot_drop_1
      - skillshot_drop_2
      - skillshot_drop_3
    rotate_events: timer_skillshot_rotate_tick

shots:
  skillshot_drop_1:
    switch: s_3_bank_drop_target_1
    advance_events: mode_skillshot_started, advance_skillshot_1
    profile: skillshot_profile
    show_tokens:
      lights: skill_shot_1, skill_shot_round
  skillshot_drop_2:
    switch: s_3_bank_drop_target_2
    advance_events: advance_skillshot_2
    profile: skillshot_profile
    show_tokens:
      lights: skill_shot_2, skill_shot_round
  skillshot_drop_3:
    switch: s_3_bank_drop_target_3
    advance_events: advance_skillshot_3
    profile: skillshot_profile
    show_tokens:
      lights: skill_shot_3, skill_shot_round

shot_profiles:
  skillshot_profile:
    advance_on_hit: false
    states:
      - name: off
        show: off
      - name: on
        show: on
      - name: lit
        show: flash



timers:
  skillshot_rotate:
    tick_interval: 500ms
    start_running: true
    control_events:
      - event: balldevice_bd_trough_ball_eject_success
        action: stop

variable_player:
  skillshot_lit_hit:
    score: 200000
  