#config_version=6

#mode: high_score

mode:
  priority: 1500
  start_events: game_ending, start_high_score
  game_mode: false
  use_wait_queue: true


event_player:
  s_right_flipper_active:
    item_highlighted:
      button: right
  s_left_flipper_active:
    item_highlighted:
      button: left
  s_start_active:
    item_highlighted:
      button: select

high_score:
  _overwrite: true
  enter_initials_timeout: 60s
  award_slide_display_time: 5s
  categories:
    score:
      - GRAND CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
      - HIGH SCORE 5
      - HIGH SCORE 6
      - HIGH SCORE 7
      - HIGH SCORE 8
  defaults:
    score:
      - LISA SUE:         60000000
      - JEFFREY:          55000000
      - PT BARNUM:        50000000
      - PHILLIP:          45000000 
      - ANNE:             40000000
      - CHARITY:          35000000
      - JENNY:            30000000
      - LETTIE:           25000000
      - CHARLES:          2000000

slide_player:
  mode_high_score_started: high_score_enter_initials
  high_score_award_display: high_score_award_display_slide
  loops_award_display: score_award_display



slides:
  _overwrite: true
  high_score_enter_initials:
    - type: text
      text: PLAYER (player_num)
      font_size: 120
      color: gold

      y: 80%
    - type: text
      font_size: 120
      text: (award)
      color: gold

      y: 65%
    - type: text_input
      char_list: ABCDEFGHIJKLMNOPQRSTUVWXYZ
      #dynamic_x: false
      key: high_score
      font_size: 120
      max_chars: 12

      y: 50%
      shift_left_event: s_left_flipper_active
      shift_right_event: s_right_flipper_active
      select_event: s_start_active
      color: gold
    - type: text
      text: ''
      key: high_score
      font_size: 120
      y: 35%
      color: gold

    - type: image
      image: bar_screen
      scale: 1
  high_score_award_display_slide:
    - type: text
      text: (player_name)
      font_size: 140
      y: 70%
      color: gold
    
    - type: text
      text: (award)
      font_size: 120
      y: 50%
      color: gold
    - type: text
      text: (value)
      y: 30%
      color: gold
      font_size: 120
      #number_grouping: true
      #min_digits: 2
    - type: image
      image: bar_screen
      scale: 1
  score_award_display:
    - type: text
      text: (player_name)
      font_size: 120
      y: 80%
      color: gold

    - type: text
      text: (award)
      font_size: 120
      y: 50%
      color: gold
    - type: text
      text: (value)
      y: 30%
      color: gold
      font_size: 120
      #number_grouping: true
      #min_digits: 2
    - type: text
      text: (player(player_num)|character)
      y: 20%
      color: gold
      font_size: 120

    - type: image
      image: bar_screen
      scale: 1








sound_player:
  high_score_enter_initials:
    high_score:
      action: play
      loops: 0 





sounds:
  high_score:
    file: high_score.wav
    track: voice
    volume: 0.9
    priority: 100
  so_talented:
    file: talented.wav
    track: voice
    volume: 0.9
    priority: 50
  
  










