#config_version=6

mode:
  priority: 1500
  start_events: game_ending, start_high_score
  game_mode: false
  use_wait_queue: true

high_score:
  _overwrite: true
  enter_initials_timeout: 60s
  award_slide_display_time: 8s
  categories:
    score:
      - GRAND CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
      - HIGH SCORE 5
      - HIGH SCORE 6
      - HIGH SCORE 7
      - HIGH SCORE 8
  defaults:
    score:
      - LISA SUE: 10000000
      - JEFFREY:   8000000
      - PT BARNUM: 6000000
      - PHILLIP:   5000000 
      - ANNE:      4000000
      - CHARITY:   3000000
      - JENNY:     2000000
      - LETTIE:    1000000
      - CHARLES:     25000












