#config_version=6

mode:
  priority: 1500
  start_events: game_ending, start_high_score
  game_mode: false
  use_wait_queue: true

high_score:
  _overwrite: true
  enter_initials_timeout: 60s
  award_slide_display_time: 8s
  categories:
    score:
      - GRAND CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
      - HIGH SCORE 5
      - HIGH SCORE 6
      - HIGH SCORE 7
      - HIGH SCORE 8
  defaults:
    score:
      - LISA SUE:  20000000
      - JEFFREY:   18000000
      - PT BARNUM: 16000000
      - PHILLIP:   14000000 
      - ANNE:      12000000
      - CHARITY:   10000000
      - JENNY:     8000000
      - LETTIE:    6000000
      - CHARLES:    250000

slide_player:
  mode_high_score_started: high_score_enter_initials
  high_score_award_display: high_score_award_display_slide
  loops_award_display: score_award_display



slides:
  _overwrite: true
  high_score_enter_initials:
    - type: text
      text: PLAYER (player_num)
      font_size: 100
      color: gold
      x: 105
      y: 90
    - type: text
      font_size: 80
      text: (award)
      color: gold
      x: 105
      y: 70
    - type: text_input
      initial_char: A
      dynamic_x: false
      key: high_score
      font_size: 80
      max_chars: 12
      x: 105
      y: 20
      shift_left_event: s_left_flipper
      shift_right_event: s_right_flipper
      select_event: s_start
      color: gold
    - type: text
      text: '<       >'
      font_size: 80
      x: 105
      y: 20
      color: gold
    - type: text
      text: ''
      key: high_score
      font_size: 80
      x: 105
      y: 50
      color: gold
    - type: image
      image: bar_screen
      scale: 1
  high_score_award_display_slide:
  #high_score_award_display:
    - type: text
      text: (player_name)
      font_size: 80
      anchor_y: middle
      anchor_x: middle
      x: middle
      y: middle
      color: gold
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.05s
          - property: opacity
            value: 0
            duration: 0.05s
            repeat: true
    - type: text
      text: (award)
      font_size: 80
      x: 105
      y: 110
      color: gold
    - type: text
      text: (value)
      x: 105
      y: 30
      color: gold
      font_size: 80
      number_grouping: true
      min_digits: 2
    - type: image
      image: bar_screen
      scale: 1
  score_award_display:
    - type: text
      text: (player_name)
      font_size: 80
      anchor_y: middle
      anchor_x: middle
      x: middle
      y: middle
      color: gold
      animations:
        show_slide:
          - property: opacity
            value: 1
            duration: 0.05s
          - property: opacity
            value: 0
            duration: 0.05s
            repeat: true
    - type: text
      text: (award)
      font_size: 80
      x: 105
      y: 110
      color: gold
    - type: text
      text: (value)
      x: 105
      y: 30
      color: gold
      font_size: 80
      number_grouping: true
      min_digits: 2
    - type: text
      text: (player(player_num)|character)
      x: 105
      y: 10
      color: gold
      font_size: 80
    - type: image
      image: bar_screen
      scale: 1
  
  










