#config_version=6

#mode: high_score

mode:
  priority: 1500
  start_events: game_ending, start_high_score
  game_mode: false
  use_wait_queue: true




high_score:
  _overwrite: true
  enter_initials_timeout: 60s
  award_slide_display_time: 5s
  categories:
    score:
      - GRAND CHAMPION
      - HIGH SCORE 1
      - HIGH SCORE 2
      - HIGH SCORE 3
      - HIGH SCORE 4
      - HIGH SCORE 5
      - HIGH SCORE 6
      - HIGH SCORE 7
      - HIGH SCORE 8
  defaults:
    score:
      - LISA SUE:         60000000
      - JEFFREY:          55000000
      - PT BARNUM:        50000000
      - PHILLIP:          45000000 
      - ANNE:             40000000
      - CHARITY:          35000000
      - JENNY:            30000000
      - LETTIE:           25000000
      - CHARLES:          2000000


slide_player:
  _overwrite: true
  high_score_enter_initials: high_score_enter_initials
  high_score_award_display: high_score_award_display


slides:
  _overwrite: true
  high_score_enter_initials:
    - type: text
      text: PLAYER (player_num)
      color: gold
      y: 80%
      font_size: 120
    - type: text
      text: (award)
      color: gold
      y: 65%
      font_size: 120
    - type: text_input
      initial_char: A
      dynamic_x: false
      key: high_score
      max_chars: 12
      shift_left_event: s_left_flipper_active
      shift_right_event: s_right_flipper_active
      select_event: s_start_active
      color: gold
      y: 50%
      font_size: 120
    - type: text
      text: '<            >'
      font_size: 120
      color: gold
      y: 50%
    - type: text
      text: ''
      key: high_score
      font_size: 120
      color: gold
      y: 42%
    - type: image
      image: bar_screen
      scale: 1

  high_score_award_display:
    - type: text
      text: (player_name)
      font_size: 140
      color: gold
      y: 70%
    - type: text
      text: (award)
      color: gold
      font_size: 120
      y: 50%
    - type: text
      text: (value)
      number_grouping: true
      min_digits: 2
      color: gold
      font_size: 120
      y: 30%
    - type: image
      image: bar_screen





sound_player:
  high_score_enter_initials:
    high_score:
      action: play
      loops: 0 





sounds:
  high_score:
    file: high_score.wav
    track: voice
    volume: 0.9
    priority: 100
  so_talented:
    file: talented.wav
    track: voice
    volume: 0.9
    priority: 50


  










