#config_version=6
mode:
  start_events: start_mode_pop_bumpers
  stop_events: timer_pop_bumpers_timer_complete
  priority: 200
event_player:
  pop_bumpers_complete: start_mode_pop_bumpers

timers:
  pop_bumpers_timer:
    start_value: 20
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: mode_pop_bumpers_started
    start_running: false

show_player:
  mode_pop_bumpers_started: 
    pop_bumpers_show:
      speed: 1
    pop_bumpers_lights:
      speed: 10


sound_player:
  mode_pop_bumpers_started:
    Pop_bumper_challenge_completed:
      action: play

variable_player:
  top_pop_bumpers_top_pop_bumpers_hit:
    score: 1000
  top_pop_bumpers_bottom_pop_bumpers_hit:
    score: 1000
  top_pop_bumpers_left_pop_bumpers_hit:
    score: 1000
  left_pop_bumpers_top_pop_bumpers_hit:
    score: 1000
  left_pop_bumpers_right_pop_bumpers_hit:
    score: 1000
  left_pop_bumpers_left_pop_bumpers_hit:
    score: 1000
  timer_pop_bumpers_timer_tick:
    pop_bumpers_timer_seconds:
      int: device.timers.pop_bumpers_timer.ticks % 60
      action: set

shots:
  top_pop_bumpers_top_pop_bumpers:
    switch: s_top_pop_bumpers_top
    profile: pop_bumpers
  top_pop_bumpers_bottom_pop_bumpers:
    switch: s_top_pop_bumpers_bottom
    profile: pop_bumpers
  top_pop_bumpers_left_pop_bumpers:
    switch: s_top_pop_bumpers_left
    profile: pop_bumpers
  left_pop_bumpers_top_pop_bumpers:
    switch: s_left_pop_bumpers_top
    profile: pop_bumpers
  left_pop_bumpers_right_pop_bumpers:
    switch: s_left_pop_bumpers_right
    profile: pop_bumpers
  left_pop_bumpers_left_pop_bumpers:
    switch: s_left_pop_bumpers_left
    profile: pop_bumpers

shot_profiles:
  pop_bumpers:
    states:
    - name: flashing
      show: flash
    loop: false
    block: true


    






  
  
  