#config_version=6
mode:
  start_events: start_mode_pop_bumpers
  stop_events: timer_pop_bumpers_timer_complete, ball_ended
  priority: 200

event_player:
  events_when_stopped: enable_qualify, start_mode_base, post_challenge_done


timers:
  pop_bumpers_timer:
    start_value: 20
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: mode_pop_bumpers_started
    start_running: false

show_player:
  mode_pop_bumpers_started: 
    pop_bumpers_show:
      speed: 1
    pop_bumpers_lights:
      speed: 8

track_player:
  mode_pop_bumpers_started:
    music:
      action: stop_all_sounds
  mode_pop_bumpers_will_stop:
    __all__:
      action: stop_all_sounds
      fade: 1s


sound_player:
  mode_pop_bumpers_started:
    Pop_bumper_challenge_completed:
      action: play
      loops: 0
    million_dreams:
      action: play
      track: music
      loops: 0
      delay: 0.1s
    shoot_pops:
      action: play
      track: voice
      delay: 5s
      loops: 0


  top_pop_bumpers_bottom_pop_bumpers_hit:
    jackpot:
      action: play
      block: true

  left_pop_bumpers_top_pop_bumpers_hit:
    jackpot:
      action: play
      block: true



  timer_pop_bumpers_timer_complete:
    million_dreams:
      action: stop
      fade_out: 1s




      
sounds:
  pop_bumper_challenge_completed:
    file: Pop_bumper_challenge_completed.wav
    track: voice
    volume: 1.7
    priority: 200
    max_queue_time: 0
  shoot_pops:
    file: shoot_pop_bumpers.wav
    track: voice
    volume: 1.5
    priority: 500
  million_dreams:
    file: million_dreams.wav
    track: music
    volume: 0.6
    priority: 800
  jackpot:
    file: jackpot.wav
    track: voice
    volume: 0.9
    priority: 1000
    block: true






variable_player:
  top_pop_bumpers_top_pop_bumpers_hit:
    score: 80000
  top_pop_bumpers_bottom_pop_bumpers_hit:
    score: 80000
  top_pop_bumpers_left_pop_bumpers_hit:
    score: 80000
  left_pop_bumpers_top_pop_bumpers_hit:
    score: 80000
  left_pop_bumpers_right_pop_bumpers_hit:
    score: 80000
  left_pop_bumpers_left_pop_bumpers_hit:
    score: 80000
  timer_pop_bumpers_timer_tick:
    pop_bumpers_timer_seconds:
      int: device.timers.pop_bumpers_timer.ticks % 60
      action: set

shots:
  top_pop_bumpers_top_pop_bumpers:
    switch: s_top_pop_bumpers_top
    #profile: pop_bumpers
  top_pop_bumpers_bottom_pop_bumpers:
    switch: s_top_pop_bumpers_bottom
    #profile: pop_bumpers
  top_pop_bumpers_left_pop_bumpers:
    switch: s_top_pop_bumpers_left
    #profile: pop_bumpers
  left_pop_bumpers_top_pop_bumpers:
    switch: s_left_pop_bumpers_top
    #profile: pop_bumpers
  left_pop_bumpers_right_pop_bumpers:
    switch: s_left_pop_bumpers_right
    #profile: pop_bumpers
  left_pop_bumpers_left_pop_bumpers:
    switch: s_left_pop_bumpers_left
    #profile: pop_bumpers

#shot_profiles:
  #pop_bumpers:
   # states:
   # - name: flashing
   #   show: flash
   # loop: false
   # block: true




    






  
  
  