#config_version=6

show_player:
  mode_attract_started: 
    attract_display_loop:
      speed: 1
    attract_light_show:
      speed: 4
    oddities_attract_show:
      speed: 2
    port_one_light_show_attract:
      speed: 3

slide_player:
  mode_attract_stopped:
    widgets:
      - type: image
        image: white_dog.png

    