#config_version=6

show_player:
  mode_attract_started: 
    attract_display_loop:
      speed: 1
    attract_light_show:
      speed: 8
    oddities_attract_show:
      speed: 8
    port_one_light_show_attract:
      speed: 8
    skill_shot_show:
      speed: 8
    challenges_attract_show:
      speed: 8
    miss_jenny_attract:
      speed: 8
    extra_ball_attract:
      speed: 8

sounds:
  attract:
    file: Attract_Mode.wav
    track: music
    volume: 0.4
    priority: 100

sound_player:
  mode_attract_started:
    attract:
      action: play
      loops: -1
  mode_attract_will_stop:
    attract:
      action: stop
    



    