#config_version=6

show_player:
  mode_attract_started: 
    attract_display_loop:
      speed: 1
    attract_light_show:
      speed: 4
    oddities_attract_show:
      speed: 4
    port_one_light_show_attract:
      speed: 4
    skill_shot_show:
      speed: 4



    