#config_version=6

mode:
  start_events: ball_started
  priority: 100

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
      - type: text
        text: 'POTATO VALUE: (potato)'
        y: 40%




variable_player:
  my_first_shot_my_first_profile_unlit_hit:
    score: 100
  my_first_shot_my_first_profile_flashing_hit:
    score: 1000
  my_first_shot_hit:
    my_first_shot: 1
  s_left_flipper_active:
    potato: 1
  s_right_flipper_active:
    potato: 1
  s_back_ramp_made_active:
    score: 100
  s_1_bank_drop_target_active:
    score: 100
  s_left_pop_bumpers_left_active:
    score: 100
  s_right_ticket_booth_active:
    score: 100
  s_left_pop_bumpers_right_active:
    score: 100
  s_left_ticket_booth_active:
    score: 100
  s_3_bank_drop_target_1_active:
    score: 100
  s_3_bank_drop_target_2_active:
    score: 100
  s_3_bank_drop_target_3_active:
    score: 100
  s_left_stand_up_target_active:
    score: 100
  s_left_pop_bumpers_top_active:
    score: 100
  s_middle_stand_up_target_active:
    score: 100
  s_top_pop_bumpers_bottom_active:
    score: 100
  s_left_orbit_top_active:
    score: 100
  s_top_pop_bumpers_left_active:
    score: 100
  s_left_orbit_bottom_active:
    score: 100
  s_inner_orbit_enter_active:
    score: 100
  s_stand_up_target_right_active:
    score: 100
  s_right_bounce_mid_playfield_active:
    score: 100
  s_right_drain_active:
    score: 100
  s_slingshot_right_active:
    score: 100
  s_left_ramp_made_acitve:
    score: 100
  s_top_pop_bumpers_top_acitve:
    score: 100
  s_spinner_active:
    score: 100
  s_left_stand_up_target_lift_ramp_active:
    score: 100
  s_right_stand_up_target_lift_ramp_active:
    score: 100
  s_right_orbit_bottom_active:
    score: 100
  s_under_ramp_eject_active:
    score: 100
  s_right_orbit_top_active:
    score: 100
  s_left_drain_active:
    score: 100
  s_slingshot_left_active:
    score: 100
  s_left_bounce_mid_playfield_active:
    score: 100
  s_left_return_lane_active:
    score: 100
  
shots:
  my_first_shot:
    switch: s_right_inlane
    show_tokens:
      lights: save_the_show_right
    profile: my_first_profile

shot_profiles:
  my_first_profile:
    states:
      - name: unlit
        show: off
      - name: flashing
        show: flash
      - name: lit
        show: on
    loop: true



