#config_version=6

mode:
  start_events: ball_started, restart_mode_base
  priority: 100

slides:
  ladies_gents:
    type: video
    video: ladies_gents
    volume: 0.3


  
    
  main_screen:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        y: 23%
      - type: text
        text: PLAYER (number)
        y: 32%
        font_size: 50
      - type: text
        text: (ball)
        x: 18%
        y: 34.7%
        color: black
        font_size: 45
      - type: text
        text: 3
        x: 25.6%
        y: 34.7%
        color: black
        font_size: 45
      - type: text
        text: (orbit)
        x: 3.2%
        y: 72%
        font_size: 33
        color: black
      - type: text
        text: 10
        x: 7.95%
        y: 72%
        font_size: 33
        color: black
      - type: text
        text: (drops)
        x: 3%
        y: 56%
        font_size: 33
        color: black
      - type: text
        text: 10
        x: 7.8%
        y: 56%
        font_size: 33
        color: black    
      - type: text
        text: (ramps)
        x: 2.9%
        y: 41.7%
        font_size: 33
        color: black
      - type: text
        text: 9
        x: 7.55%
        y: 41.7%
        font_size: 33
        color: black  
      - type: text
        text: (tickets)
        x: 2.6%
        y: 25.7%
        font_size: 33
        color: black
      - type: text
        text: 10
        x: 7.5%
        y: 25.7%
        font_size: 33
        color: black  
      - type: text
        text: (pop)
        x: 2.6%
        y: 10%
        font_size: 33
        color: black
      - type: text
        text: 200
        x: 7.32%
        y: 10%
        font_size: 25
        color: black  
      - type: image
        image: main_screen
        scale: 1


slide_player:
  play_ladies_gents_slide:
    ladies_gents    
  play_main_screen_slide:
    main_screen
  remove_ladies_gents_slide:
    ladies_gents: 
      action: remove

      



    

videos:
  ladies_gents:
    file: ladies_gents.mpg



variable_player:
 # my_first_shot_my_first_profile_unlit_hit:
    #score: 100
  #my_first_shot_my_first_profile_flashing_hit:
   # score: 1000
 # my_first_shot_hit:
   # my_first_shot: 1
  s_left_flipper_active:
    potato: 1
  s_right_flipper_active:
    potato: 1
  right_ramp_hit:
    score: 165000
    ramps: 1
    bonus_ramps: 1
  single_drop_target_hit:
    score: 250000
    drops: 1
  left_pop_bumpers_left_hit:
    score: 16500
    pop: 1
  s_right_ticket_booth_active:
    score: 0
  left_pop_bumpers_right_hit:
    score: 16500
    pop: 1
  tickets_hit:
    score: 25000
    tickets: 1
  front_drop_target_hit:
    score: 35000
    drops: 1
  #3_bank_drop_target_2_hit:
  middle_drop_target_hit:
    score: 35000
    drops: 1
  back_drop_target_hit:
    score: 35000
    drops: 1
  s_left_stand_up_target_active:
    score: 130000
  left_pop_bumpers_top_hit:
    score: 16500
    pop: 1
  s_middle_stand_up_target_active:
    score: 130000
  top_pop_bumpers_bottom_hit:
    score: 16500
    pop: 1
  left_orbit_hit:
    score: 165000
    orbit: 1
  top_pop_bumpers_left_hit:
    score: 16500
    pop: 1
  inner_orbit_hit:
    score: 165000
    orbit: 1
  s_stand_up_target_right_active:
    score: 130000
  s_right_bounce_mid_playfield_active:
    score: 5000
  s_right_drain_active:
    score: 165000
  s_slingshot_right_active:
    score: 16500
  left_ramp_hit:
    score: 165000
    ramps: 1
    bonus_ramps: 1
  top_pop_bumpers_top_hit:
    score: 16500
    pop: 1
  s_spinner_active:
    score: 5000
  s_left_stand_up_target_lift_ramp_active:
    score: 130000
  s_right_stand_up_target_lift_ramp_active:
    score: 130000
  s_under_ramp_eject_active:
    score: 1000
  right_orbit_hit:
    score: 165000
    orbit: 1
  s_left_drain_active:
    score: 165000
  s_slingshot_left_active:
    score: 16500
  s_left_bounce_mid_playfield_active:
    score: 5000
  s_left_return_lane_active:
    score: 16500
  s_right_inlane_active:
    score: 165
  challenges_done:
    score: 25000
  mode_pop_bumpers_starting:
    bonus_challenges: 1
  mode_drop_targets_starting:
    bonus_challenges: 1
  mode_orbits_starting:
    bonus_challenges: 1
  mode_ramps_starting:
    bonus_challenges: 1
  mode_tickets_starting:
    bonus_challenges: 1  
  drop_bank_up_hit:
    score: 1000000
    drop_bonus: 1
  drop_bank_down_hit:
    score: 1000000
    drop_bonus: 1


shots:
 # my_first_shot:
   # switch: s_right_inlane
    #show_tokens:
     # lights: save_the_show_right
    #profile: my_first_profile
#POP BUMPERS
  top_pop_bumpers_top:
    switch: s_top_pop_bumpers_top

    tags: upper_pops
  top_pop_bumpers_bottom:
    switch: s_top_pop_bumpers_bottom

    tags: upper_pops
  top_pop_bumpers_left:
    switch: s_top_pop_bumpers_left

    tags: upper_pops
  left_pop_bumpers_top:
    switch: s_left_pop_bumpers_top

  left_pop_bumpers_right:
    switch: s_left_pop_bumpers_right

  left_pop_bumpers_left:
    switch: s_left_pop_bumpers_left


#ORBITS
  shot_left_orbit:
    enable_events: left_orbit_hit
  shot_right_orbit:
    enable_events: right_orbit_hit
  shot_inner_orbit: 
    enable_events: inner_orbit_hit

#DROP TARGETS

  single_drop_target:
    switch: s_single_drop_target

  front_drop_target:
    switch: s_3_bank_drop_target_1

  middle_drop_target:
    switch: s_3_bank_drop_target_2

  back_drop_target:
    switch: s_3_bank_drop_target_3

#TICKET BOOTHS

  tickets:
    switch: s_left_ticket_booth

#RAMPS
  left_ramp:
    switch: s_left_ramp_made

  right_ramp:
    switch: s_back_ramp_made



ball_saves:
  default:
    active_time: 20s
    hurry_up_time: 8s
    grace_period: 2s
    enable_events: mode_base_started
    timer_start_events: ball_device_bd_plunger_ball_eject_success
    auto_launch: true
    #balls_to_save: -1
    only_last_ball: true
    



shot_profiles:
  #my_first_profile:
    #states:
      #- name: unlit
       # show: off
      #- name: flashing
      #  show: flash
      #- name: lit
       # show: on
    #loop: true



sequence_shots:
  left_orbit:
    switch_sequence: s_left_orbit_bottom, s_left_orbit_top, s_right_orbit_top
    sequence_timeout: 3s
  right_orbit:
    switch_sequence: s_right_orbit_bottom, s_right_orbit_top, s_left_orbit_top
    sequence_timeout: 3s
  inner_orbit:
    switch_sequence: s_inner_orbit_enter, s_right_orbit_top, s_right_orbit_bottom
    sequence_timeout: 3s
  drop_bank_up:
    switch_sequence: s_3_bank_drop_target_1, s_3_bank_drop_target_2, s_3_bank_drop_target_3
    sequence_timeout: 1s
  drop_bank_down:
    switch_sequence: s_3_bank_drop_target_3, s_3_bank_drop_target_2, s_3_bank_drop_target_1
    sequence_timeout: 1s


event_player:
  mode_base_started{current_player.ball==1 and current_player.number==1}:
    - play_ladies_gents_slide
    - remove_ladies_gents_slide|6s
    - play_main_screen_slide|6.1s

  mode_base_started{current_player.ball>1 or current_player.number>1}:
    - play_main_screen_slide





  post_pop_mode_starting_events:
    start_mode_pop_bumpers:
      priority: 1
    enable_pop_achievement:
      priority: 2
    start_pop_achievement:
      priority: 3
    complete_pop_achievement:
      priority: 4
  post_orbits_mode_starting_events:
    start_mode_orbits:
      priority: 1
    enable_orbits_achievement:
      priority: 2
    start_orbits_achievement:
      priority: 3
    complete_orbits_achievement:
      priority: 4
  post_drop_targets_mode_starting_events:
    start_mode_drop_targets:
      priority: 1
    enable_drop_targets_achievement:
      priority: 2
    start_drop_targets_achievement:
      priority: 3
    complete_drop_targets_achievement:
      priority: 4
  post_tickets_mode_starting_events:
    start_mode_tickets:
      priority: 1
    enable_tickets_achievement:
      priority: 2
    start_tickets_achievement:
      priority: 3
    complete_tickets_achievement:
      priority: 4
  post_ramps_mode_starting_events:
    start_mode_ramps:
      priority: 1
    enable_ramps_achievement:
      priority: 2
    start_ramps_achievement:
      priority: 3
    complete_ramps_achievement:
      priority: 4

  events_when_started:
    enable_qualify


    


show_player:
  left_pop_bumpers_left_hit:
    single_flash_color:
      show_tokens:
        lights: hat_left_pop_bumpers
        color: snow
      loops: 0
      priority: 10000
  left_pop_bumpers_right_hit:
    single_flash_color:
      show_tokens:
        lights: hat_left_pop_bumpers
        color: snow
      loops: 0
      priority: 10000
  left_pop_bumpers_top_hit:
    single_flash_color:
      show_tokens:
        lights: hat_left_pop_bumpers
        color: snow
      loops: 0
      priority: 10000
  top_pop_bumpers_top_hit:
    single_flash_color:
      show_tokens:
        lights: hat_upper_pop_bumpers
        color: snow
      loops: 0
      priority: 10000
  top_pop_bumpers_left_hit:
    single_flash_color:
      show_tokens:
        lights: hat_upper_pop_bumpers
        color: snow
      loops: 0
      priority: 10000
  top_pop_bumpers_bottom_hit:
    single_flash_color:
      show_tokens:
        lights: hat_upper_pop_bumpers
        color: snow
      loops: 0
      priority: 10000
  ball_device_bd_plunger_ejecting_ball:
    single_flash_color:
      show_tokens:
        lights: save_the_show_right, save_the_show_left
        color: red
      action: play
      speed: 5
      loops: 20
  #mode_challenges_will_stop: #this didn't work, but the sound and score part did
    #challenges_done:
     # speed: 1
     # loops: 0
     # priority: 1000
   # challenges_done_lights:
      #speed: 1
    #  loops: 0
     # priority: 1000
  

      


shows:
  single_flash_color:
    - duration: 200ms
      lights:
        (lights): (color) #use snow for white
  1_lit_color_generic:
    - duration: -1
      lights:
        (lights): (color)
  color_flashing:
    - duration: 200ms
      lights:
        (lights): (color)
    - duration: 200ms
      lights: 
        (lights): 
          color: black



sound_player:
  mode_base_started{current_player.ball==1 and current_player.number==1}:
    first_ball_music:
      action: play
      delay: 6.1s
      loops: -1

  mode_base_started{current_player.ball>1 or current_player.number>1}:
    first_ball_music:
      action: play
      loops: -1

  mode_pop_bumpers_started:
    first_ball_music:
      action: stop
      fade_out: 0.5s
  mode_tickets_started:
    first_ball_music:
      action: stop
      fade_out: 0.5s
  mode_drop_targets_started:
    first_ball_music:
      action: stop
      fade_out: 0.5s
  mode_orbits_started:
    first_ball_music:
      action: stop
      fade_out: 0.5s
  mode_ramps_started:
    first_ball_music:
      action: stop
      fade_out: 0.5s

  mode_base_started:
    the_other_side:
      action: stop
      fade_out: 1s
    a_million_dreams:
      action: stop
      fade_out: 1s
    come_alive:
      action: stop
      fade_out: 1s
    from_now_on:
      action: stop
      fade_out: 1s
    this_is_me:
      action: stop
      fade_out: 1s

  mode_pop_bumpers_stopped:
    first_ball_music:
      action: play
      loops: -1
  mode_ramps_stopped:
    first_ball_music:
      action: play
      loops: -1
  mode_orbits_stopped:
    first_ball_music:
      action: play
      loops: -1
  mode_drop_targets_stopped:
    first_ball_music:
      action: play
      loops: -1
  mode_tickets_stopped:
    first_ball_music:
      action: play
      loops: -1
  s_right_bounce_mid_playfield_active:
    elephant:
      action: play
      loops: 0
  s_left_bounce_mid_playfield_active:
    whip:
      action: play
      loops: 0

  single_drop_target_hit:
    merry_1:
      action: play
      loops: 0

  front_drop_target_hit:
    merry_2:
      action: play
      loops: 0

  middle_drop_target_hit:
    merry_3:
      action: play
      loops: 0

  back_drop_target_hit:
    merry_4:
      action: play
      loops: 0
  s_spinner_active:
    spinner:
      action: play
      loops: 0  
  s_stand_up_target_right_active:  
    train:
      action: play
      loops: 0  
  left_pop_bumpers_left_hit:
    explosion:
      action: play
      loops: 0  
  left_pop_bumpers_top_hit:
    explosion:
      action: play
      loops: 0  
  left_pop_bumpers_right_hit:
    explosion:
      action: play
      loops: 0  
  top_pop_bumpers_top_hit:
    explosion:
      action: play
      loops: 0  
  top_pop_bumpers_left_hit:
    explosion:
      action: play
      loops: 0  
  top_pop_bumpers_bottom_hit:
    explosion:
      action: play
      loops: 0  
  right_ramp_hit:
    never_enough:
      action: play
      loops: 0  
  left_ramp_hit:
    left_ramp:
      action: play
      loops: 0 
  #mode_challenges_will_stop:
    #so_talented:
     # action: play
     # loops: 0
  ball_save_default_saving_ball:
    ball_save_callout:
      action: play
      loops: 0

   

sounds:
  first_ball_music:
    file: ball1_player1_5.wav
    track: music
    volume: 0.9
    priority: 100
  elephant:
    file: Elephant_Angry.wav
    track: sfx
    volume: 0.6
    priority: 50
  whip:
    file: bull_whip.wav
    track: sfx
    volume: 0.6
    priority: 50
  merry_1:
    file: merry_1.wav
    track: sfx
    volume: 0.6
    priority: 50
  merry_2:
    file: merry_2.wav
    track: sfx
    volume: 0.6
    priority: 50
  merry_3:
    file: merry_3.wav
    track: sfx
    volume: 0.6
    priority: 50
  merry_4:
    file: merry_4.wav
    track: sfx
    volume: 0.6
    priority: 50
  spinner:
    file: spinner.wav
    track: sfx
    volume: 0.8
    priority: 50
  train:
    file: train.wav
    track: sfx
    volume: 0.6
    priority: 50
  explosion:
    file: explosion.wav
    track: sfx
    volume: 0.6
    priority: 50
  never_enough:
    file: Never_Enough.wav
    track: sfx
    volume: 0.8
    priority: 50
  left_ramp:
    file: ramp_lion.wav
    track: sfx
    volume: 0.8
    priority: 50
  so_talelented:
    file: so_talented.wav
    track: voice
    volume: 0.8
    priority: 1000
  you_cant_quit:
    file: you_cant_quit.wav
    track: voice
    volume: 0.8
    priority: 1000
  the_show_is_saved:
    file: the_show_is_saved.wav
    track: voice
    volume: 0.8
    priority: 1000
  the_show_must_go_on:
    file: the_show_must_go_on.wav
    track: voice
    volume: 0.8
    priority: 1000
  the_show_must_go_on_2:
    file: the_show_must_go_on_2.wav
    track: voice
    volume: 0.8
    priority: 1000
  is_this_how_weve_taught_you:
    file: is_this_how_weve_taught_you.wav
    track: voice
    volume: 0.8
    priority: 1000

sound_pools:
  ball_save_callout:
    type: random
    track: voice
    sounds:
      - is_this_how_weve_taught_you
      - the_show_must_go_on
      - the_show_is_saved
      - the_show_must_go_on_2
      - you_cant_quit

    

track_player:
  ball_ending:
    music:
      action: stop_all_sounds
      fade: 1s
    voice:
      action: stop_all_sounds
  game_ending:
    music:
      action: stop_all_sounds
      fade: 1s
    voice:
      action: stop_all_sounds


    
      


    
    
  




  
















