#config_version=6

mode:
  start_events: ball_started
  priority: 100

slides:
  ladies_gents:
    type: video
    video: ladies_gents
    #expire: 7s
  main_screen:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        y: 23%
      - type: text
        text: PLAYER (number)
        y: 32%
        font_size: 50
      - type: text
        text: (ball)
        x: 18%
        y: 34.7%
        color: black
        font_size: 45
      - type: text
        text: 3
        x: 25.6%
        y: 34.7%
        color: black
        font_size: 45
      - type: text
        text: (orbit)
        x: 3.2%
        y: 72%
        font_size: 33
        color: black
      - type: text
        text: 10
        x: 7.95%
        y: 72%
        font_size: 33
        color: black
      - type: text
        text: (drops)
        x: 3%
        y: 56%
        font_size: 33
        color: black
      - type: text
        text: 10
        x: 7.8%
        y: 56%
        font_size: 33
        color: black    
      - type: text
        text: (ramps)
        x: 2.9%
        y: 41.7%
        font_size: 33
        color: black
      - type: text
        text: 9
        x: 7.55%
        y: 41.7%
        font_size: 33
        color: black  
      - type: text
        text: (tickets)
        x: 2.6%
        y: 25.7%
        font_size: 33
        color: black
      - type: text
        text: 10
        x: 7.5%
        y: 25.7%
        font_size: 33
        color: black  
      - type: text
        text: (pop)
        x: 2.6%
        y: 10%
        font_size: 33
        color: black
      - type: text
        text: 200
        x: 7.32%
        y: 10%
        font_size: 25
        color: black  
      - type: image
        image: main_screen
        scale: 1

slide_player:
  mode_base_started: 
    ladies_gents    
  remove_ladies_gents_slide:
    ladies_gents: 
      action: remove
  play_main_screen_slide:
    main_screen
   
  #mode_base_started:
   # main_screen
    

videos:
  ladies_gents:
    file: ladies_gents.mpg



variable_player:
  my_first_shot_my_first_profile_unlit_hit:
    score: 100
  my_first_shot_my_first_profile_flashing_hit:
    score: 1000
  my_first_shot_hit:
    my_first_shot: 1
  s_left_flipper_active:
    potato: 1
  s_right_flipper_active:
    potato: 1
  right_ramp_hit:
    score: 100
    ramps: 1
  single_drop_target_hit:
    score: 100
    drops: 1
  left_pop_bumpers_left_hit:
    score: 100
    pop: 1
  s_right_ticket_booth_active:
    score: 100
  left_pop_bumpers_right_hit:
    score: 100
    pop: 1
  tickets_hit:
    score: 100
    tickets: 1
  front_drop_target_hit:
    score: 100
    drops: 1
  #3_bank_drop_target_2_hit:
  middle_drop_target_hit:
    score: 100
    drops: 1
  back_drop_target_hit:
    score: 100
    drops: 1
  s_left_stand_up_target_active:
    score: 100
  left_pop_bumpers_top_hit:
    score: 100
    pop: 1
  s_middle_stand_up_target_active:
    score: 100
  top_pop_bumpers_bottom_hit:
    score: 100
    pop: 1
  left_orbit_hit:
    score: 100
    orbit: 1
  top_pop_bumpers_left_hit:
    score: 100
    pop: 1
  inner_orbit_hit:
    score: 100
    orbit: 1
  s_stand_up_target_right_active:
    score: 100
  s_right_bounce_mid_playfield_active:
    score: 100
  s_right_drain_active:
    score: 100
  s_slingshot_right_active:
    score: 100
  left_ramp_hit:
    score: 100
    ramps: 1
  top_pop_bumpers_top_hit:
    score: 100
    pop: 1
  s_spinner_active:
    score: 100
  s_left_stand_up_target_lift_ramp_active:
    score: 100
  s_right_stand_up_target_lift_ramp_active:
    score: 100
  s_under_ramp_eject_active:
    score: 100
  right_orbit_hit:
    score: 100
    orbit: 1
  s_left_drain_active:
    score: 100
  s_slingshot_left_active:
    score: 100
  s_left_bounce_mid_playfield_active:
    score: 100
  s_left_return_lane_active:
    score: 100
  
shots:
 # my_first_shot:
   # switch: s_right_inlane
    #show_tokens:
     # lights: save_the_show_right
    #profile: my_first_profile
#POP BUMPERS
  top_pop_bumpers_top:
    switch: s_top_pop_bumpers_top

    tags: upper_pops
  top_pop_bumpers_bottom:
    switch: s_top_pop_bumpers_bottom

    tags: upper_pops
  top_pop_bumpers_left:
    switch: s_top_pop_bumpers_left

    tags: upper_pops
  left_pop_bumpers_top:
    switch: s_left_pop_bumpers_top

  left_pop_bumpers_right:
    switch: s_left_pop_bumpers_right

  left_pop_bumpers_left:
    switch: s_left_pop_bumpers_left


#ORBITS
  shot_left_orbit:
    enable_events: left_orbit_hit
  shot_right_orbit:
    enable_events: right_orbit_hit
  shot_inner_orbit: 
    enable_events: inner_orbit_hit

#DROP TARGETS

  single_drop_target:
    switch: s_single_drop_target

  front_drop_target:
    switch: s_3_bank_drop_target_1

  middle_drop_target:
    switch: s_3_bank_drop_target_2

  back_drop_target:
    switch: s_3_bank_drop_target_3

#TICKET BOOTHS

  tickets:
    switch: s_left_ticket_booth

#RAMPS
  left_ramp:
    switch: s_left_ramp_made

  right_ramp:
    switch: s_back_ramp_made







shot_profiles:
  #my_first_profile:
    #states:
      #- name: unlit
       # show: off
      #- name: flashing
      #  show: flash
      #- name: lit
       # show: on
    #loop: true



sequence_shots:
  left_orbit:
    switch_sequence: s_left_orbit_bottom, s_left_orbit_top, s_right_orbit_top
    sequence_timeout: 3s
  right_orbit:
    switch_sequence: s_right_orbit_bottom, s_right_orbit_top, s_left_orbit_top
    sequence_timeout: 3s
  inner_orbit:
    switch_sequence: s_inner_orbit_enter, s_right_orbit_top, s_right_orbit_bottom
    sequence_timeout: 3s


event_player:
  post_pop_mode_starting_events:
    start_mode_pop_bumpers:
      priority: 1
    enable_pop_achievement:
      priority: 2
    start_pop_achievement:
      priority: 3
    complete_pop_achievement:
      priority: 4
  post_orbits_mode_starting_events:
    start_mode_orbits:
      priority: 1
    enable_orbits_achievement:
      priority: 2
    start_orbits_achievement:
      priority: 3
    complete_orbits_achievement:
      priority: 4
  post_drop_targets_mode_starting_events:
    start_mode_drop_targets:
      priority: 1
    enable_drop_targets_achievement:
      priority: 2
    start_drop_targets_achievement:
      priority: 3
    complete_drop_targets_achievement:
      priority: 4
  post_tickets_mode_starting_events:
    start_mode_tickets:
      priority: 1
    enable_tickets_achievement:
      priority: 2
    start_tickets_achievement:
      priority: 3
    complete_tickets_achievement:
      priority: 4
  post_ramps_mode_starting_events:
    start_mode_ramps:
      priority: 1
    enable_ramps_achievement:
      priority: 2
    start_ramps_achievement:
      priority: 3
    complete_ramps_achievement:
      priority: 4
  #ball_started{ball==1 and player==1}:
    #- play_show_ball_one
     # priority: 10000
  #base_mode_started:
    #enable_challenges_selection


  mode_base_started{current_player.ball==1}:
    - remove_ladies_gents_slide|6s
    - play_main_screen_slide|6.1s
  mode_base_started{balls_played>1}:
    - play_main_screen_slide

  events_when_started:
    enable_qualify

    


show_player:
  left_pop_bumpers_left_hit:
    single_flash_color:
      show_tokens:
        lights: hat_left_pop_bumpers
        color: snow
      loops: 0
      priority: 10000
  left_pop_bumpers_right_hit:
    single_flash_color:
      show_tokens:
        lights: hat_left_pop_bumpers
        color: snow
      loops: 0
      priority: 10000
  left_pop_bumpers_top_hit:
    single_flash_color:
      show_tokens:
        lights: hat_left_pop_bumpers
        color: snow
      loops: 0
      priority: 10000
  top_pop_bumpers_top_hit:
    single_flash_color:
      show_tokens:
        lights: hat_upper_pop_bumpers
        color: snow
      loops: 0
      priority: 10000
  top_pop_bumpers_left_hit:
    single_flash_color:
      show_tokens:
        lights: hat_upper_pop_bumpers
        color: snow
      loops: 0
      priority: 10000
  top_pop_bumpers_bottom_hit:
    single_flash_color:
      show_tokens:
        lights: hat_upper_pop_bumpers
        color: snow
      loops: 0
      priority: 10000

  #ball_started{current_player.ball==1}: 
    #ladies_gents
  #mode_base_started:
   # game_start_slides

      


shows:
  single_flash_color:
    - duration: 200ms
      lights:
        (lights): (color) #use snow for white
  1_lit_color_generic:
    - duration: -1
      lights:
        (lights): (color)
  color_flashing:
    - duration: 200ms
      lights:
        (lights): (color)
    - duration: 200ms
      lights: 
        (lights): 
          color: black

  #game_start_slides:
    #- duration: 6s
     # slides: ladies_gents
    #- duration: 30m
      #slides: main_screen







  
















