#config_version=6

mode:
  start_events: ball_started
  priority: 100

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        y: 23%
      - type: text
        text: PLAYER (number)
        y: 32%
        font_size: 50
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
      - type: text
        text: 'ORBIT HITS: (orbit)'
        y: 50%
        font_size: 50
      - type: image
        image: main_screen
        scale: .95




variable_player:
  my_first_shot_my_first_profile_unlit_hit:
    score: 100
  my_first_shot_my_first_profile_flashing_hit:
    score: 1000
  my_first_shot_hit:
    my_first_shot: 1
  s_left_flipper_active:
    potato: 1
  s_right_flipper_active:
    potato: 1
  s_back_ramp_made_active:
    score: 100
  1_bank_drop_target_hit:
    score: 100
  left_pop_bumpers_left_hit:
    score: 100
  s_right_ticket_booth_active:
    score: 100
  left_pop_bumpers_right_hit:
    score: 100
  s_left_ticket_booth_active:
    score: 100
  s_3_bank_drop_target_1_active:
    score: 100
  s_3_bank_drop_target_2_active:
    score: 100
  s_3_bank_drop_target_3_active:
    score: 100
  s_left_stand_up_target_active:
    score: 100
  left_pop_bumpers_top_hit:
    score: 100
  s_middle_stand_up_target_active:
    score: 100
  top_pop_bumpers_bottom_hit:
    score: 100
  left_orbit_hit:
    score: 100
    orbit: 1
  top_pop_bumpers_left_hit:
    score: 100
  inner_orbit_enter_hit:
    score: 100
    orbit: 1
  s_stand_up_target_right_active:
    score: 100
  s_right_bounce_mid_playfield_active:
    score: 100
  s_right_drain_active:
    score: 100
  s_slingshot_right_active:
    score: 100
  s_left_ramp_made_acitve:
    score: 100
  top_pop_bumpers_top_hit:
    score: 100
  s_spinner_active:
    score: 100
  s_left_stand_up_target_lift_ramp_active:
    score: 100
  s_right_stand_up_target_lift_ramp_active:
    score: 100
  s_under_ramp_eject_active:
    score: 100
  right_orbit_hit:
    score: 100
    orbit: 1
  s_left_drain_active:
    score: 100
  s_slingshot_left_active:
    score: 100
  s_left_bounce_mid_playfield_active:
    score: 100
  s_left_return_lane_active:
    score: 100
  
shots:
  my_first_shot:
    switch: s_right_inlane
    show_tokens:
      lights: save_the_show_right
    profile: my_first_profile
  top_pop_bumpers_top:
    switch: s_top_pop_bumpers_top
    show_tokens:
      lights: hat_upper_pop_bumpers
    profile: top_pop_bumpers_top_profile
  top_pop_bumpers_bottom:
    switch: s_top_pop_bumpers_bottom
    show_tokens:
      lights: hat_upper_pop_bumpers
    profile: top_pop_bumpers_bottom_profile
  top_pop_bumpers_left:
    switch: s_top_pop_bumpers_left
    show_tokens:
      lights: hat_upper_pop_bumpers
    profile: top_pop_bumpers_left_profile
  left_pop_bumpers_top:
    switch: s_left_pop_bumpers_top
    show_tokens:
      lights: hat_left_pop_bumpers
    profile: left_pop_bumpers_top_profile
  left_pop_bumpers_right:
    switch: s_left_pop_bumpers_right
    show_tokens:
      lights: hat_left_pop_bumpers
    profile: left_pop_bumpers_right_profile
  left_pop_bumpers_left:
    switch: s_left_pop_bumpers_left
    show_tokens:
      lights: hat_left_pop_bumpers
    profile: left_pop_bumpers_left_profile
  inner_orbit_enter:
    switch: s_inner_orbit_enter
    show_tokens:
      lights: arrow_left_inner_orbit
    profile: inner_orbit_enter_profile
  shot_left_orbit:
    enable_events: left_orbit_hit
    show_tokens:
      lights: arrow_outer_left_orbit, hat_left_pop_bumpers
    profile: shot_left_orbit_profile
  shot_right_orbit:
    enable_events: right_orbit_hit
    show_tokens:
      lights: arrow_right_orbit, hat_right_orbit
    profile: shot_right_orbit_profile
  shot_1_bank_drop_target:
    enable_events: 1_bank_drop_target_hit
    show_tokens:
      lights: four, three, two, one, light_extra_ball, extra_ball

shot_profiles:
  my_first_profile:
    states:
      - name: unlit
        show: off
      - name: flashing
        show: flash
      - name: lit
        show: on
    loop: true
  top_pop_bumpers_top_profile:
    states:
      - name: flashing
        show: flash
  top_pop_bumpers_bottom_profile:
    states:
      - name: flashing
        show: flash
  top_pop_bumpers_left_profile:
    states:
      - name: flashing
        show: flash
  left_pop_bumpers_top_profile:
    states:
      - name: flashing
        show: flash
  left_pop_bumpers_right_profile:
    states:
      - name: flashing
        show: flash
  left_pop_bumpers_left_profile:
    states:
      - name: flashing
        show: flash
  inner_orbit_enter_profile:
    states:
      - name: flashing
        show: flash
  shot_left_orbit_profile:
    states:
      - name: flashing
        show: flash
  shot_right_orbit_profile:
    states:
      - name: flashing
        show: flash




sequence_shots:
  left_orbit:
    switch_sequence: s_left_orbit_bottom, s_left_orbit_top
    sequence_timeout: 3s
  right_orbit:
    switch_sequence: s_right_orbit_bottom, s_right_orbit_top
    sequence_timeout: 3s











