#config_version=6
mode:
  #start when base starts
  start_events: mode_base_started
  #test mode, low priority
  priority: 1

shots:
  #define these mode-specefic shots using switch names provide by Lisa
  #this is the shot name
  gg_top_pop_top:
    #switch to go with the shot
    switch: top_pop_bumpers_top
    
  gg_top_pop_left:
    switch: top_pop_bumpers_left
    
  gg_top_pop_right:
    switch: top_pop_bumpers_right

#this is a show player. It watches for events, then fires the named show
show_player:
  #when the event from the pop bumper shot is hit
  gg_top_pop_top_hit:
    #play this show
    - gg_show

#repeat for other two pops
  gg_top_pop_right_hit:
    - gg_show
  
  gg_top_pop_left_hit:
    - gg_show