#config_version=6

mode:
  start_events: start_mode_orbits
  stop_events: timer_orbits_timer_complete, ball_ended
  priority: 200

event_player:
  events_when_stopped: enable_qualify, start_mode_base


timers:
  orbits_timer:
    start_value: 20
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: mode_orbits_started
    start_running: false


show_player:
  mode_orbits_started: 
    orbits_show:
      speed: 1
    orbits_light_show:
      speed: 10

sound_player:
  mode_orbits_started:
    orbits_completed:
      action: play
      track: voice
      loops: 0
    from_now_on:
      action: play
      track: music
      loops: 0

    shoot_orbits:
      action: play
      delay: 5s
      track: voice
      loops: 0


sounds:
  orbits_completed:
    file: shoot_pop_bumpers.wav
    track: voice
    volume: 1.5
    priority: 200
  shoot_orbits:
    file: shoot_orbits.wav
    track: voice
    volume: 1.5
    priority: 200
  from_now_on:
    file: From_Now_On.wav
    track: music
    volume: 0.2
    priority: 200

  





variable_player:
  inner_orbit_enter_orbits_hit:
    score: 1000
  shot_right_orbit_orbits_hit:
    score: 1000
  shot_left_orbit_hit:
    score: 1000
  timer_orbits_timer_tick:
    orbits_timer_seconds:
      int: device.timers.orbits_timer.ticks % 60
      action: set


shots:
   inner_orbit_enter_orbits:
    switch: s_inner_orbit_enter 
   shot_left_orbit_orbits:
    enable_events: left_orbit_hit
    show_tokens:
      lights: arrow_outer_left_orbit, hat_left_pop_bumpers
   shot_right_orbit_orbits:
    enable_events: right_orbit_hit
    show_tokens:
      lights: arrow_right_orbit, hat_right_orbit
