#config_version=6

mode:
  start_events: start_mode_orbits
  stop_events: timer_orbits_timer_complete
  priority: 200
event_player:
  pop_bumpers_complete: start_mode_orbits

timers:
  orbits_timer:
    start_value: 20
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: mode_orbits_started
    start_running: false

show_player:
  mode_orbits_started: 
    orbits_show:
      speed: 1
    orbits_lights:
      speed: 10

sound_player:
  mode_pop_bumpers_started:
    orbits_challenge_completed:
      action: play

variable_player:
  top_pop_bumpers_top_pop_bumpers_hit:
    score: 1000
  top_pop_bumpers_bottom_pop_bumpers_hit:
    score: 1000
  top_pop_bumpers_left_pop_bumpers_hit:
    score: 1000
  left_pop_bumpers_top_pop_bumpers_hit:
    score: 1000
  left_pop_bumpers_right_pop_bumpers_hit:
    score: 1000
  left_pop_bumpers_left_pop_bumpers_hit:
    score: 1000
  timer_pop_bumpers_timer_tick:
    pop_bumpers_timer_seconds:
      int: device.timers.pop_bumpers_timer.ticks % 60
      action: set