#config_version=6

mode:
  start_events: start_mode_orbits
  stop_events: timer_orbits_timer_complete
  priority: 200
event_player:
  orbits_complete: start_mode_orbits

timers:
  orbits_timer:
    start_value: 20
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: mode_orbits_started
    start_running: false

show_player:
  mode_orbits_started: 
    orbits_show:
      speed: 1
    orbits_light_show:
      speed: 10

sound_player:
  mode_orbits_started:
    orbits_challenge_completed_1:
      action: play

variable_player:
  inner_orbit_enter_orbits_hit:
    score: 1000
  right_orbit_orbits_hit:
    score: 1000
  shot_left_orbit_hit:
    score: 1000
  orbits_bumpers_timer_tick:
    orbits_timer_seconds:
      int: device.timers.orbits_timer.ticks % 60
      action: set

shots:
   inner_orbit_enter_orbits:
    switch: s_inner_orbit_enter 
   shot_left_orbit_orbits:
    enable_events: left_orbit_hit
    show_tokens:
      lights: arrow_outer_left_orbit, hat_left_pop_bumpers
   shot_right_orbit_orbits:
    enable_events: right_orbit_hit
    show_tokens:
      lights: arrow_right_orbit, hat_right_orbit
