#config_version=6
mode:
  start_events: start_mode_drop_targets
  stop_events: timer_drop_targets_timer_complete, ball_ended 
  priority: 200

event_player:
  events_when_stopped: enable_qualify, start_mode_base

timers:
  drop_targets_timer:
    start_value: 20
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: mode_drop_targets_started
    start_running: false

show_player:
  mode_drop_targets_started: 
    drop_targets_show:
      speed: 1
    drop_targets_lights:
      speed: 10

track_player:
  mode_drop_targets_started:
    music:
      action: stop_all_sounds
  mode_drop_targets_will_stop:
    __all__:
      action: stop_all_sounds
      fade: 1s



sound_player:
  mode_drop_targets_started:

    drop_targets_challenge_completed:
      action: play
      track: voice
      loops: 0
    the_other_side:
      action: play
      track: music
      loops: 0
      delay: 0.1s
    shoot_drop_targets:
      action: play
      track: voice
      delay: 5s
      loops: 0
  timer_drop_targets_timer_complete:
    the_other_side:
      action: stop
      fade_out: 1s 
  
sounds:
  drop_targets_challenge_completed:
    file: drop_targets_done.wav
    track: voice
    volume: 1.5
    priority: 500
  shoot_drop_targets:
    file: shoot_drops_now.wav
    track: voice
    volume: 1.5
    priority: 500


  the_other_side:
    file: The_Other_Side.wav
    track: music
    volume: 0.6
    priority: 800

  
  

variable_player:
  single_drop_target_drop_targets_hit:
    score: 175000
  front_drop_target_drop_targets_hit:
    score: 175000
  middle_drop_target_drop_targets_hit:
    score: 175000
  back_drop_target_drop_targets_hit:
    score: 175000
  timer_drop_targets_timer_tick:
    drop_targets_timer_seconds:
      int: device.timers.drop_targets_timer.ticks % 60
      action: set

shots:
  single_drop_target_drop_targets:
    switch: s_single_drop_target
  front_drop_target_drop_targets:
    switch: s_3_bank_drop_target_1
  middle_drop_target_drop_targets:
    switch: s_3_bank_drop_target_2
  back_drop_target_drop_targets:
    switch: s_3_bank_drop_target_3
  
