#config_version=6
mode:
  start_events: start_mode_drop_targets
  stop_events: timer_drop_targets_timer_complete
  priority: 200



timers:
  drop_targets_timer:
    start_value: 20
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: mode_drop_targets_started
    start_running: false

show_player:
  mode_drop_targets_started: 
    drop_targets_show:
      speed: 1
    drop_targets_lights:
      speed: 10


sound_player:
  mode_drop_targets_started:
    drop_target_challenge_completed:
      action: play

variable_player:
  single_drop_target_drop_targets_hit:
    score: 1000
  3_bank_drop_target_1_drop_targets_hit:
    score: 1000
  3_bank_drop_target_2_drop_targets_hit:
    score: 1000
  3_bank_drop_target_3_drop_targets_hit:
    score: 1000
  timer_drop_targets_timer_tick:
    drop_targets_timer_seconds:
      int: device.timers.drop_targets_timer.ticks % 60
      action: set

shots:
  single_drop_target_drop_targets:
    switch: s_single_drop_target
  3_bank_drop_target_1_drop_targets:
    switch: s_3_bank_drop_target_1
  3_bank_drop_target_2_drop_targets:
    switch: s_3_bank_drop_target_2
  3_bank_drop_target_3_drop_targets:
    switch: s_3_bank_drop_target_2
  
