#config_version=6

mode:
  start_events: ball_ending
  #code: bonus.Bonus
  priority: 500


mode_settings: 
  display_delay_ms: 1000ms
  hurry_up_delay_ms: 200ms
  bonus_entries:
    - event: bonus_challenges
      score: 250000
      player_score_entry: bonus_challenges
    - event: bonus_ramps
      score: 50000
      player_score_entry: bonus_ramps
    - event: drop_bonus
      score: 150000
      player_score_entry: drop_bonus

slide_player:
  mode_bonus_started: bonus_start_slide
  bonus_challenges: bonus_challenges_slide
  bonus_ramps: bonus_ramps_slide
  drop_bonus: bonus_drop_slide
  bonus_total: bonus_total_slide

slides:
  bonus_start_slide:
    widgets:
    - type: text
      text: Bonus
      font_size: 150
      color: black
    - type: image
      image: curtains
      scale: 1

  bonus_challenges_slide:
    widgets: 
    - type: text
      text: "Challenges Completed"
      y: 70%
      font_size: 150
      color: black
    - type: text
      text: "(player|bonus_challenges)x"
      y: 50%
      color: black
      font_size: 140
    - type: text
      text: (score)
      y: 30%
      font_size: 140
      color: black
    - type: image
      image: curtains
      scale: 1

  bonus_ramps_slide:
    widgets:
    - type: text
      text:  "Ramps Hit"
      y: 70%
      color: black
      font_size: 150
    - type: text
      text: "(player|bonus_ramps)x"
      y: 50%
      color: black
      font_size: 140
    - type: text
      text: (score)
      y: 30%
      font_size: 140
      color: black
    - type: image
      image: curtains
      scale: 1

  bonus_drop_slide:
    widgets:
    - type: text
      text:  "Drop Target Sweeps"
      y: 70%
      color: black
      font_size: 150
    - type: text
      text: "(player|drop_bonus)x"
      y: 50%
      color: black
      font_size: 140
    - type: text
      text: (score)
      y: 30%
      font_size: 140
      color: black
    - type: image
      image: curtains
      scale: 1


  bonus_total_slide:
    widgets:
    - type: text
      text: Total Bonus
      y: 60%
      font_size: 130
      color: black
    - type: text
      text: (score)
      y: 40%
      font_size: 140
      color: black
    - type: image
      image: curtains
      scale: 1


    
  