#config_version=6
mode:
  start_events: start_mode_irish_giant
  stop_events: irish_giant_complete, game_ending #ball_ended
  restart_on_next_ball: true
  events_when_stopped: start_mode_lord_of_leeds
  priority: 200




shots:
  left_orbit_irish_giant:  #B
    switch: s_left_orbit_bottom
    show_tokens:
      lights: arrow_outer_left_orbit
      color: green
    profile: irish_giant_profile
    advance_events: left_orbit_irish_giant_flashing_hit
    control_events:
      - events: advance_irish_giant_profile
        state: 2
  left_return_irish_giant:  #A
    switch: s_left_return_lane
    show_tokens:
      lights: arrow_bottom_left
      color: green
    profile: irish_giant_profile
    advance_events: left_return_irish_giant_flashing_hit
    control_events:
      - events: advance_irish_giant_profile
        state: 2   
  right_stand_up_irish_giant:  #E
    switch: s_stand_up_target_right
    show_tokens:
      lights: target_mid_right
      color: green
    profile: irish_giant_profile
    advance_events: right_stand_up_irish_giant_flashing_hit
    control_events: 
      - events: advance_irish_giant_profile
        state: 2 
  



 





shot_profiles:
  irish_giant_profile:
    states:
      - name: flashing
        show: green_flashing
      - name: lit
        show: irish_giant_lit
      - name: unlit
        show: off
    advance_on_hit: false



shows:
  green_flashing:
    - duration: 200ms
      lights:
        (lights):
          color: green
    - duration: 200ms
      lights: 
        (lights): 
          color: black
  irish_giant_lit:
    - duration: -1
      lights: 
       (lights):
         color: green 



counters:
  irish_giant_counter:
    starting_count: 0
    count_events: left_orbit_irish_giant_flashing_hit, left_return_irish_giant_flashing_hit, right_stand_up_irish_giant_flashing_hit
    count_complete_value: 3
    start_enabled: true
    persist_state: true
    reset_on_complete: false 
    events_when_complete: advance_irish_giant_profile, light_oddities_4, irish_giant_complete 
    #restart_events:  #five_million_standup_five_million_profile_lit_hit




variable_player:
  left_orbit_irish_giant_flashing_hit:
    score: 500000
  left_return_irish_giant_flashing_hit:
    score: 500000
  right_stand_up_irish_giant_flashing_hit:
    score: 500000
  advance_irish_giant_profile:
    score: 1000000





sounds:
  collect_8_oddities:
    file: collect_8_oddities.wav
    track: voice
    volume: 1.5
    priority: 1000
  shoot_the_colored_arrows:
    file: shoot_the_colored_arrows
    track: voice
    volume: 1.5
    priority: 1000
  rewrite_the_stars:
    file: rewrite_the_stars.wav
    track: music
    volume: 0.5
    priority: 900


sound_player:
  play_collect_8_oddities:
    collect_8_oddities:
      action: play
      priority: 1000
  play_shoot_the_colored_arrows:
    shoot_the_colored_arrows:
      action: play
      priority: 1000
  play_rewrite_the_stars:
    rewrite_the_stars:
      action: play
      priority: 1000  




slides:
  main_screen_tom_thumb:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        y: 22%
      - type: text
        text: PLAYER (number)
        y: 32%
        font_size: 50
      - type: text
        text: (ball)
        x: 18%
        y: 34.7%
        color: black
        font_size: 45
      - type: text
        text: 3
        x: 25.6%
        y: 34.7%
        color: black
        font_size: 45
      - type: text
        text: (orbit)
        x: 3.2%
        y: 72%
        font_size: 33
        color: black
      - type: text
        text: 4
        x: 7.95%
        y: 72%
        font_size: 33
        color: black
      - type: text
        text: (drops)
        x: 3%
        y: 56%
        font_size: 33
        color: black
      - type: text
        text: 10
        x: 7.8%
        y: 56%
        font_size: 33
        color: black    
      - type: text
        text: (ramps)
        x: 2.9%
        y: 41.7%
        font_size: 33
        color: black
      - type: text
        text: 4
        x: 7.55%
        y: 41.7%
        font_size: 33
        color: black  
      - type: text
        text: (tickets)
        x: 2.6%
        y: 25.7%
        font_size: 33
        color: black
      - type: text
        text: 8
        x: 7.5%
        y: 25.7%
        font_size: 33
        color: black  
      - type: text
        text: (pop)
        x: 2.6%
        y: 10%
        font_size: 33
        color: black
      - type: text
        text: 80
        x: 7.32%
        y: 10%
        font_size: 25
        color: black  
      - type: text
        text: (player1|score)
        x: 20%
        y: 9%
        color: white
        font_size: 60
        number_grouping: true
      - type: text
        text: (player2|score)
        x: 40%
        y: 9%
        color: white
        font_size: 60
        number_grouping: true
      - type: text
        text: (player3|score)
        x: 59%
        y: 9%
        color: white
        font_size: 60
        number_grouping: true
      - type: text
        text: (player4|score)
        x: 78%
        y: 9%
        color: white
        font_size: 60
        number_grouping: true
      - type: image
        image: main_screen_tom_thumb
        scale: 1

      


slide_player:
  remove_main_screen_dog_boy_slide:
    main_screen_dog_boy:
      action: remove
  play_main_screen_tom_thumb_slide:
    main_screen_tom_thumb
  remove_main_screen_slide:
    main_screen:
      action: remove








event_player:
  mode_irish_giant_started:
    - remove_main_screen_slide
    - remove_main_screen_dog_boy_slide
    - play_main_screen_tom_thumb_slide|6.2s
    - play_collect_8_oddities|7.25s
    - play_shoot_the_colored_arrows|8s
    - play_rewrite_the_stars|10s

  restart_mode_irish_giant:
    - remove_main_screen_slide
    - remove_main_screen_dog_boy_slide
    - play_main_screen_tom_thumb_slide


track_player:
  mode_irish_giant_started:
    music:
      action: stop_all_sounds
  mode_irish_giant_will_stop:
    __all__:
      action: stop_all_sounds
      fade: 1s

