#config_version=6
mode:
  start_events: game_started, ball_started

shots:
#EXTRA BALL SEQUENCE
#4
  light_number_4:
    switch: s_single_drop_target
    show_tokens: 
      lights: four
      color: snow
    profile: extra_ball_profile
    advance_events: advance_light_four
    control_events:
      - events: extra_ball_lit_hit
        state: 0


shot_profiles:
  extra_ball_profile:
    states:
      - name: unlit
        show: off
      - name: flashing
        show: white_flashing
      - name: lit
        show: green_lit
    advance_on_hit: false



shows:

  green_lit:
    - duration: -1
      lights: 
       (lights):
         color: green

  white_flashing:
    - duration: 200ms
      lights:
        (lights):
          color: snow
    - duration: 200ms
      lights: 
        (lights): 
          color: black     

counters:
#EXTRA BALL COUNTERS
  light_four_counter1:
    starting_count: 0
    count_events: single_drop_target_hit
    count_complete_value: 1
    start_enabled: true
    events_when_complete: advance_light_four
    persist_state: true
    reset_on_complete: false
  light_four_counter2:
    starting_count: 0
    count_events: single_drop_target_hit
    count_complete_value: 2
    start_enabled: true
    events_when_complete: advance_light_four
    persist_state: true
    reset_on_complete: false  










