#config_version=6
mode:
  start_events: game_started, ball_started

shots:
#EXTRA BALL SEQUENCE
#4
  light_number_4:
    switch: s_single_drop_target
    show_tokens: 
      lights: four
      color: snow
    profile: extra_ball_profile
    advance_events: advance_light_four
    control_events:
      - events: extra_ball_lit_hit
        state: 0
#3
  light_number_3:
    switch: s_single_drop_target
    show_tokens: 
      lights: three
      color: snow
    profile: extra_ball_profile
    advance_events: advance_light_three
    control_events:
      - events: extra_ball_lit_hit
        state: 0
#2
  light_number_2:
    switch: s_single_drop_target
    show_tokens: 
      lights: two
      color: snow
    profile: extra_ball_profile
    advance_events: advance_light_two
    control_events:
      - events: extra_ball_lit_hit
        state: 0
#1
  light_number_1:
    switch: s_single_drop_target
    show_tokens: 
      lights: one
      color: snow
    profile: extra_ball_profile
    advance_events: advance_light_one
    control_events:
      - events: extra_ball_lit_hit
        state: 0
#light_extra_ball
  light_light_extra_ball:
    switch: s_single_drop_target
    show_tokens: 
      lights: light_extra_ball
      color: snow
    profile: extra_ball_profile
    advance_events: advance_light_light_extra_ball
    control_events:
      - events: extra_ball_lit_hit
        state: 0
#extra_ball
  light_extra_ball:
    switch: s_single_drop_target
    show_tokens: 
      lights: extra_ball
      color: snow
    profile: extra_ball_profile
    advance_events: advance_light_extra_ball
    control_events:
      - events: extra_ball_lit_hit
        state: 0

#shoot_again
  light_shoot_again:
    switch: s_single_drop_target
    show_tokens:
      lights: shoot_again
    profile: shoot_again_profile
    advance_events: extra_ball_lit_hit
    control_events:
      - events: #start extra ball??
        state: 0


shot_profiles:
  extra_ball_profile:
    states:
      - name: unlit
        show: off
      - name: flashing
        show: white_flashing
      - name: lit
        show: green_lit

    advance_on_hit: false

  shoot_again_profile:
    states: 
      - name: unlit
        show: off
      - name: lit
        show: red_lit
        
 

shows:
  green_lit:
    - duration: -1
      lights: 
       (lights):
         color: green

  white_flashing:
    - duration: 200ms
      lights:
        (lights):
          color: snow
    - duration: 200ms
      lights: 
        (lights): 
          color: black 
  red_lit:
    - duration: -1
      lights: 
       (lights):
         color: red    

counters:
#EXTRA BALL COUNTERS
  extra_ball_counter1:
    starting_count: 0
    count_events: single_drop_target_hit
    count_complete_value: 1
    start_enabled: true
    events_when_complete: advance_light_four
    persist_state: true
    reset_on_complete: false
  extra_ball_counter2:
    starting_count: 0
    count_events: single_drop_target_hit
    count_complete_value: 2
    start_enabled: true
    events_when_complete: advance_light_four, advance_light_three
    persist_state: true
    reset_on_complete: false  
  extra_ball_counter3:
    starting_count: 0
    count_events: single_drop_target_hit
    count_complete_value: 3
    start_enabled: true
    events_when_complete: advance_light_three, advance_light_two
    persist_state: true
    reset_on_complete: false  

  extra_ball_counter4:
    starting_count: 0
    count_events: single_drop_target_hit
    count_complete_value: 4
    start_enabled: true
    events_when_complete: advance_light_two, advance_light_one
    persist_state: true
    reset_on_complete: false  
  extra_ball_counter5:
    starting_count: 0
    count_events: single_drop_target_hit
    count_complete_value: 5
    start_enabled: true
    events_when_complete: advance_light_one, advance_light_light_extra_ball
    persist_state: true
    reset_on_complete: false  
  extra_ball_counter6:
    starting_count: 0
    count_events: single_drop_target_hit
    count_complete_value: 6
    start_enabled: true
    events_when_complete: advance_light_light_extra_ball, advance_light_extra_ball, extra_ball_lights
    persist_state: true
    reset_on_complete: false  
  extra_ball_counter7:
    starting_count: 0
    count_events: single_drop_target_hit
    count_complete_value: 7
    start_enabled: true
    events_when_complete: extra_ball_lit_hit
    persist_state: true
    reset_on_complete: false  

show_player:
  extra_ball_lights:
    extra_ball_lights:
      loops: -1
      speed: 8
      priority: 1000
  extra_ball_lit_hit:
    extra_ball_lights:
      action: stop

extra_balls:
  extra_ball_main:
    award_events: extra_ball_lit_hit

variable_player:
  extra_ball_lit_hit:
    score: 1000000
 

sounds:
    extra_ball:
    file: extra_ball.wav
    track: voice
    volume: 0.8
    priority: 1000
    extra_ball_is_lit:
    file: extra_ball_is_lit.wav
    track: voice
    volume: 0.8
    priority: 1000

sound_player:
  extra_ball_lights:
    extra_ball_is_lit:
      action: play
      loops: 0
  extra_ball_lit_hit:
    extra_ball:
      action: play
      loops: 0

  







