#config_version=6

mode:
  start_events: ball_started

achievements:
  pop_bumpers:
    show_tokens:
      lights: challenges_e
      color: red
    show_when_started: 1_lit_color_generic
    show_when_completed: 1_lit_color_generic
    enable_events: enable_pop_achievement
    start_events: start_pop_achievement
    events_when_started: pop_bumpers_achievement_started
    complete_events: complete_pop_achievement
    reset_events: reset_pop_bumpers

  orbits:
    show_tokens:
      lights: challenges_a
      color: red
    show_when_started: 1_lit_color_generic
    show_when_completed: 1_lit_color_generic
    enable_events: enable_orbits_achievement
    start_events: start_orbits_achievement
    events_when_started: orbits_achievement_started
    complete_events: complete_orbits_achievement
    reset_events: reset_orbits

  drop_targets:
    show_tokens:
      lights: challenges_b
      color: red
    show_when_started: 1_lit_color_generic
    show_when_completed: 1_lit_color_generic
    enable_events: enable_drop_targets_achievement
    start_events: start_drop_targets_achievement
    events_when_started: drop_targets_achievement_started
    complete_events: complete_drop_targets_achievement
    reset_events: reset_drop_targets

achievement_groups:
  challenges:
    achievements: pop_bumpers, orbits, drop_targets
    show_tokens:
      lights: challenges_f
      color: red
    #show_when_completed: 1_lit_color_generic
     


     






