#config_version=6

mode:
  start_events: ball_started

achievements:
  pop_bumpers:
    show_tokens:
      lights: challenges_e
      color: red
    show_when_started: 1_lit_color_generic
    show_when_completed: 1_lit_color_generic
    enable_events: enable_pop_achievement
    start_events: start_pop_achievement
    events_when_started: pop_bumpers_achievement_started
    complete_events: complete_pop_achievement
    reset_events: reset_pop_bumpers




shows:
  single_flash_color:
    - duration: 120ms
      lights:
        (lights): (color)
  1_lit_color_generic:
    - duration: -1
      lights:
        (lights): (color)

