#config_version=6

hardware:
    platoform: fast

fast:
  net:
    controller: neuron
    io-loop:
        1616:
            model:  FP-I/O-1616-2A 
            order:  1
        1616:
            model:  FP-I/O-1616-2A 
            order:  2
        3208:
            model:  FP-I/)-3208
            order:  3
         


