#config_version=6

hardware:
  platform: fast

fast:
  net:
    controller: neuron
    io_loop:
      "0":
        model: FP-I/O-1616-2A
        order: 1
      1:
        model: FP-I/O-1616-2A
        order: 2
      2:
        model: FP-I/O-3208-3
        order: 3
    port: auto
    baud: 921600
    debug: false
    watchdog: 1s
    default_quick_debounce_open: 2ms
    default_quick_debounce_close: 2ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms

  exp:
    boards:
      playfield:
        model: FP-EXP-0071
        led_fade_time: 32ms

    
    



switches:
  s_left_flipper: #left flipper
    number: 0-5
    tags: left_flipper
    debounce: quick
  s_right_flipper: #right flipper
    number: 0-1
    tags: right_flipper
    debounce: quick
  s_right_upper_flipper: #right upper flipper
    number: 0-0
    tags: right_upper_flipper
    debounce: quick
  s_trough1: #trough 1
    number: 2-10
    type: NC
  s_trough2: #trough 2
    number: 2-9
    type: NC
  s_trough3: #trough 3
    number: 2-8
    type: NC
  s_trough4: #trough 4
    number: 2-13
    type: NC
  s_trough5: #trough 5
    number: 2-12
    type: NC
  s_trough6: #trough 6
    number: 2-11
    type: NC
  s_trough_jam: #trough jam
    number: 2-14
    type: NC
  s_plunger: #plunger or shooter lane
    number: 2-5
  s_start: #start
    number: 0-7
    tags: start
  s_right_inlane: #right inlane or return lane
    number: 2-6
    tags: playfield_active
  s_back_ramp_made: #back ramp made
    number: 0-2
    tags: playfield_active
  s_tilt: #tilt
    number: 0-6
    tags: tilt_warning
  s_single_drop_target: #1 bank drop target
    number: 1-0
    type: NO
    platform_settings:
      debounce_open: 100ms
      debounce_close: 255ms
  s_left_pop_bumpers_left: #left pop bumper left
    number: 1-1
    debounce: quick
  s_right_ticket_booth:  #right ticket booth
    number: 1-2
  s_left_pop_bumpers_right:  #left pop bumpers right
    number: 1-3
    debounce: quick
  s_left_ticket_booth:  #left ticket booth
    number: 1-4
  s_3_bank_drop_target_1: # 3 bank drop target 1
    number: 1-5
    type: NO
  s_3_bank_drop_target_2: #3 bank drop target 2
    number: 1-6
    type: NO
  s_3_bank_drop_target_3: #3 bank drop target 3
    number: 1-7
    type: NO
  s_left_stand_up_target: #left stand up target near ticket booth
    number: 1-8
    tags: playfield_active
    debounce: quick
    ignore_window_ms: 1000ms
  s_left_pop_bumpers_top: #left pop bumpers top
    number: 1-9
    debounce: quick
  s_middle_stand_up_target:  #middle stand up target below upper pop bumper
    number: 1-10
    tags: playfield_active
    debounce: quick
    ignore_window_ms: 1000ms
  s_top_pop_bumpers_bottom:  #top pop bumpers bottom
    number: 1-11
    debounce: quick
  s_left_orbit_top: #left orbit top
    number: 1-12
    tags: playfield_active
  s_top_pop_bumpers_left: #top pop bumpers left
    number: 1-13
    debounce: quick
  s_left_orbit_bottom: #left orbit bottom
    number: 1-14
    tags: playfield_active
  s_inner_orbit_enter: #inner orbit enter
    number: 1-15
    tags: playfield_active
  s_stand_up_target_right: #stand up target right
    number: 2-0
    tags: playfield_active
    debounce: quick
    ignore_window_ms: 1000ms
  s_upper_right_flipper_eos:  #upper right flipper end of stroke
    number: 2-1
  s_right_bounce_mid_playfield: # right bounce mid playfield
    number: 2-2
    tags: playfield_active
  s_right_drain: #right drain
    number: 2-3
    tags: playfield_active
  s_right_flipper_eos: #right flipper end of stroke 
    number: 2-4
  s_slingshot_right: #slingshot right
    number: 2-7
    debounce: quick
  s_left_ramp_made: #left ramp made
    number: 2-15
    tags: playfield_active
  s_top_pop_bumpers_top: #top pop bumpers top
    number: 2-16
    debounce: quick
  s_spinner: #spinner
    number: 2-17
  s_left_stand_up_target_lift_ramp: #left stand up target lift ramp
    number: 2-18
    tags: playfield_active
  s_right_stand_up_target_lift_ramp: #right stand up target lift ramp
    number: 2-19
    tags: playfield_active
  s_right_orbit_bottom: #right orbit bottom
    number: 2-20
    tags: playfield_active
  s_ramp_down: # ramp down
    number: 2-21
  s_under_lift_ramp_eject: #under lift ramp eject
    number: 2-22
  s_right_orbit_top: #right orbit top
    number: 2-23
    tags: playfield_active
  s_left_drain:  #left drain
    number: 2-24
    tags: playfield_active
  s_left_lock_upper: #left lock upper
    number: 2-25
  s_left_lock_mid: #left lock mid
    number: 2-26
  s_left_lock_lower: #left lock lower
    number: 2-27
    ignore_window_ms: 5000ms
  s_slingshot_left: #slingshot left
    number: 2-28
    debounce: quick
  s_left_bounce_mid_playfield: #left bounce mid playfield
    number: 2-29
    tags: playfield_active
  s_left_flipper_eos: #left flipper end of stroke
    number: 2-30
  s_left_return_lane: #left return lane
    number: 2-31
    tags: playfield_active


virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3


keyboard:
  z:
    switch: s_left_flipper
  '/':
    switch: s_right_flipper
  s:
    switch: s_start
  q:
    switch: s_right_inlane
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  4:
    switch: s_trough4
    toggle: true
  5:
    switch: s_trough5
    toggle: true
  p:
    switch: s_plunger
    toggle: true
  n:
    event: mode2_start
  m:
    event: mode2_stop


coils:
  c_flipper_left_main: #left flipper main
    number: 2-3 #mid lug
    default_pulse_ms: 25
  c_flipper_left_hold: #left flipper hold
    number: 2-4 #outer lug
    allow_enable: true
  c_flipper_right_main: #right flipper main
    number: 2-1 #mid lug
    default_pulse_ms: 25
  c_flipper_right_hold: #right flipper hold
    number: 2-2 #outer lug
    allow_enable: true
  c_flipper_right_upper_main: #right upper flipper main
    number: 1-0
    default_pulse_ms: 25
  c_flipper_right_upper_hold:  #right upper flipper hold
    number: 1-1
    allow_enable: true
  c_trough_eject: #trough eject
    number: 2-7
    default_pulse_ms: 20
  c_plunger: #plunger or shooter lane
    number: 2-0
    default_pulse_ms: 12
  c_3_spinning_dics_motor_red:  #3 spinning discs red
    number: 0-0
    default_hold_power: 0.25
    max_hold_power: 0.5
  c_ramp_up: #ramp up
    number: 1-2
    default_pulse_ms: 255
    default_pulse_power: 1.0
  c_ramp_down:  # ramp down
    number: 1-3
    default_pulse_ms: 200
    default_pulse_power: 1.0
  c_under_ramp_eject: #under ramp eject
    number: 1-4
    #default_pulse_ms: 15ms
    default_hold_power: 1.0
  c_top_pop_bumpers_bottom:  #top pop bumpers bottom
    number: 1-5
  c_top_pop_bumpers_top:  #top pop bumpers top
    number: 1-6
  c_top_pop_bumpers_left: #top pop bumpers left
    number: 1-8
  c_3_drop_target_reset: # 3 drop target reset
    number: 1-9
    default_pulse_ms: 30
  c_left_pop_bumpers_top: # left pop bumpers top
    number: 1-10
  c_left_pop_bumpers_right: #left pop bumpers right
    number: 1-11
  c_left_pop_bumpers_left: #left pop bumpers left
    number: 1-12
  c_ticket_booth_eject: #ticket booth eject
    number: 1-13
    default_pulse_ms: 75ms
    default_pulse_power: 1.0
  c_ramp_diverter: #ramp diverter
    number: 1-14
    default_hold_power: 0.5
  c_triple_lock_eject: #triple lock eject
    number: 1-15
    default_pulse_ms: 50ms
    default_pulse_power: 1
  c_right_slingshot: #right slingshot
    number: 2-5
    default_pulse_ms: 20
    platform_settings:
      recycle_ms: 40
  c_left_slingshot: #left slingshot
    number: 2-6
    default_pulse_ms: 20
    platform_settings:
      recycle_ms: 40
  c_single_drop_target_reset: #single drop target reset
    number: 1-7
    default_pulse_ms: 25
    platform_settings:
      recycle_ms: 100

lights:
  top_right_eject: #under lift ramp
    number: playfield-1-1
    type: rgb
  hat_right_orbit: 
    number: playfield-1-2
    type: rgb
  arrow_right_orbit:
    number: playfield-1-3
    type: rgb
  arrow_lift_ramp_target_right:
    number: playfield-1-4
    type: rgb
  lock:
    number: playfield-1-5
    type: rgb
  arrow_lift_ramp_target_left:
    number: playfield-1-6
    type: rgb
  lind:
    number: playfield-1-7
    type: rgb
  jenny:
    number: playfield-1-8
    type: rgb
  miss: 
    number: playfield-1-9
    type: rgb
  arrow_left_inner_orbit:
    number: playfield-1-10
    type: rgb
  hat_upper_pop_bumpers:
    number: playfield-1-11
    type: rgb
    tags: upper_pops
  extra_ball:
    number: playfield-1-12
    type: rgb
  light_extra_ball:
    number: playfield-1-13
    type: rgb
  one:
    number: playfield-1-14
    type: rgb
  two:
    number: playfield-1-15
    type: rgb
  five_million_when_lit:
    number: playfield-1-16
    type: rgb
  three:
    number: playfield-1-17
    type: rgb
  four:
    number: playfield-1-18
    type: rgb
  skill_shot_1:
    number: playfield-2-1
    type: rgb
  target_mid_right:
    number: playfield-2-2
    type: rgb
  collect_oddities_2:
    number: playfield-2-3
    type: rgb
  collect_oddities_3:
    number: playfield-2-4
    type: rgb
  collect_oddities_4:
    number: playfield-2-5
    type: rgb
  collect_oddities_5:
    number: playfield-2-6
    type: rgb
  target_mid_left:
    number: playfield-2-7
    type: rgb
  collect_oddities_6:
    number: playfield-2-8
    type: rgb
  skill_shot_round:
    number: playfield-2-9
    type: rgb
  skill_shot_3:
    number: playfield-2-10
    type: rgb
  collect_oddities_7:
    number: playfield-2-11
    type: rgb
  collect_oddities_8:
    number: playfield-2-12
    type: rgb
  collect_oddities_1:
    number: playfield-2-13
    type: rgb
  skill_shot_2:
    number: playfield-2-14
    type: rgb
  below_lock_in_musical_staff:
    number: playfield-2-15
    type: rgb
  hat_left_pop_bumpers:
    number: playfield-2-16
    type: rgb
  arrow_outer_left_orbit:
    number: playfield-2-17
    type: rgb
  save_the_show_right:
    number: playfield-3-1
    type: rgb
  challenges_f:
    number: playfield-3-2
    type: rgb
  challenges_e:
    number: playfield-3-3
    type: rgb
  challenges_d:
    number: playfield-3-4
    type: rgb
  challenges_c:
    number: playfield-3-5
    type: rgb
  challenges_b:
    number: playfield-3-6
    type: rgb
  challenges_a:
    number: playfield-3-7
    type: rgb
  shoot_again:
    number: playfield-3-8
    type: rgb
  save_the_show_left:
    number: playfield-3-9
    type: rgb
  arrow_bottom_left:
    number: playfield-3-10
    type: rgb
  ball_1_locked:
    number: playfield-3-11
    type: grb
  ball_2_locked:
    number: playfield-3-12
    type: grb
  ball_3_locked:
    number: playfield-3-13
    type: grb
 

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger
    enable_ball_search: true

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper 
    eos_switch: s_left_flipper_eos
    use_eos: true
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    eos_switch: s_right_flipper_eos
    use_eos: true
  upper_right_flipper:
    main_coil: c_flipper_right_upper_main
    hold_coil: c_flipper_right_upper_hold
    activation_switch: s_right_upper_flipper
    eos_switch: s_upper_right_flipper_eos
    use_eos: true
    

displays:
  window:
    width: 1920
    height: 1080
    

slides:
  welcome_slide:
    widgets:
      - type: text
        text: Greatest Showman Custom Pinball
        font_size: 100
        font_name: CarnivaleeFreakshow-DLrm
        color: red
      - type: image
        image: curtains
        scale: .9


slide_player:
  init_done: welcome_slide



ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 20ms
    eject_targets: bd_plunger
    eject_timeouts: 3s
  bd_plunger:
    ball_switches: s_plunger
    eject_coil: c_plunger
    mechanical_eject: true
    eject_timeouts: 3s
  bd_ticket_booth: 
    ball_switches: s_left_ticket_booth
    eject_coil: c_ticket_booth_eject
    eject_timeouts: 2s
  bd_under_ramp:
    ball_switches: s_under_lift_ramp_eject
    eject_coil: c_under_ramp_eject
    eject_timeouts: 2s
  bd_ball_lock:
    ball_switches: s_left_lock_upper, s_left_lock_mid, s_left_lock_lower
    eject_coil: c_triple_lock_eject
    eject_timeouts: 2s


autofire_coils:
  left_slingshot:
    coil: c_left_slingshot
    switch: s_slingshot_left
  right_slingshot:
    coil: c_right_slingshot
    switch: s_slingshot_right
  left_pop_bumpers_left:
    coil: c_left_pop_bumpers_left
    switch: s_left_pop_bumpers_left
  left_pop_bumpers_right:
    coil: c_left_pop_bumpers_right
    switch: s_left_pop_bumpers_right
  left_pop_bumpers_top:
    coil: c_left_pop_bumpers_top
    switch: s_left_pop_bumpers_top
  top_pop_bumpers_bottom:
    coil: c_top_pop_bumpers_bottom
    switch: s_top_pop_bumpers_bottom
  top_pop_bumpers_left:
    coil: c_top_pop_bumpers_left
    switch: s_top_pop_bumpers_left
  top_pop_bumpers_top:
    coil: c_top_pop_bumpers_top
    switch: s_top_pop_bumpers_top

drop_targets:
  single_drop_target:
    switch: s_single_drop_target
    reset_coil: c_single_drop_target_reset
    reset_events: game_started, ball_started, single_drop_target_hit
  front_drop_target:
    switch: s_3_bank_drop_target_1
  middle_drop_target:
    switch: s_3_bank_drop_target_2
  back_drop_target:
    switch: s_3_bank_drop_target_3

drop_target_banks:
  3_drop_target_bank:
    drop_targets: front_drop_target, middle_drop_target, back_drop_target
    reset_coil: c_3_drop_target_reset
    reset_on_complete: 1s
    reset_events: game_started, ball_started

diverters:
  #ramp_up_down_coils:
    #activation_coil: c_ramp_up
   # deactivation_coil: c_ramp_down
    #type: pulse
   # enable_events: stand_ups_hit
    #activate_events: stand_ups_hit
   # deactivation_switches: s_under_lift_ramp_eject
   # disable_events: s_under_ramp_eject_active_hit



  ramp_diverter_coil:
    activation_coil: c_ramp_diverter
    type: hold
    activation_time: 1.5s
    activation_switches: s_left_ramp_made
    enable_events: ramp_lock
    disable_events: left_lock_upper_hit, ball_ended 
  lock_empty_coil:
    activation_coil: c_triple_lock_eject
    type: pulse
    enable_events: eject_balls
    activate_events: eject_balls



  spinning_discs_motor:
    activation_coil: c_3_spinning_dics_motor_red
    type: hold
    activation_time: 5s
    activation_switches: s_back_ramp_made, s_stand_up_target_right
    enable_events: right_ramp_hit, multiball_inner_orbit_hit, right_stand_up_hit
    activate_events: right_ramp_hit, multiball_inner_orbit_hit, right_stand_up_hit


modes:
  - base
  - mode2
  - qualify
  - pop_bumpers
  - challenges
  - orbits
  - drop_targets
  - tickets
  - ramps
  - bonus
  - tilt
  - high_score
  - skillshot
  - challenges_multiball
  - this_is_me_multiball
  - extra_ball
  - bearded_lady
  - dog_boy
  - tom_thumb
  - irish_giant
  - lord_of_leeds
  - siamese_twins
  - trapeze_artist
  - tattooed_man

  
player_vars:
  potato:
    initial_value: 0 
  pop:
    initial_value: 0
  tickets:
    initial_value: 0
  drops:
    initial_value: 0
  ramps:
    initial_value: 0
  orbit: 
    initial_value: 0
  ball:
    initial_value: 0

machine_vars:
  master_volume:
    initial_value: 0.8
    value_type: float
    persist: true

sound_system:
  buffer: 1024
  channels: 1
  enabled: true
  frequency: 44100
  tracks:
    music:
      type: standard
      simultaneous_sounds: 2
      volume: 0.5
    voice:
      type: standard
      simultaneous_sounds: 2 
      volume: 0.7
    sfx:
      type: standard
      simultaneous_sounds: 8
      volume: 0.4

assets:
  sounds:
    default:
      load: on_demand
    music:
      track: music
    sfx:
      track: sfx
    voice:
      track: voice
  videos:
    default:
      load: on_demand



widget_styles:
  attract_mode_high_score_display_label:
    font_size: 30
    anchor_x: right
    anchor_y: top
    x: center-10
    bold: true
  attract_mode_high_score_display_name:
    font_size: 30
    anchor_x: right
    anchor_y: top
    x: center+70
  attract_mode_high_score_display_score:
    font_size: 30
    anchor_x: left
    anchor_y: top
    x: center+90
    number_grouping: true
    min_digits: 1




  


    

  
    

    



           