#config_version=6

switches:
    s_left_flipper:
        number: cab-6
        tags: left_flipper
    s_right_flipper:
        number: cab-1
        tags: right_flipper

coils:
    c_flipper_left_main:
        number: 3208-3 #mid lug
        default_pulse_ms: 20
    c_flipper_left_hold:
        number: 3208-4 #outer lug
        allow_enable: true
    c_flipper_right_main:
        number: 3208-1 #mid lug
        default_pulse_ms: 20
    c_flipper_right_hold:
        number: 3208-2 #outer lug
        allow_enable: true

playfields:
    playfield:
        tags: default
        default_source_device:  None

flippers:
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
        enable_events: machine_reset_phase_3
    right_flipper:
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
        enable_events: machine_reset_phase_3
    

         


