#config_version=6

hardware:
  platform: smart_virtual

switches:
  s_left_flipper:
    number: 0-6
    tags: left_flipper
  s_right_flipper:
    number: 0-1
    tags: right_flipper
  s_right_upper_flipper:
    number: 0-0
    tags: right_upper_flipper
  s_trough1:
    number: 2-40
    type: NC
  s_trough2:
    number: 2-41
    type: NC
  s_trough3:
    number: 2-42
    type: NC
  s_trough4:
    number: 2-43
    type: NC
  s_trough5:
    number: 2-44
    type: NC
  s_trough6:
    number: 2-45
    type: NC
  s_trough_jam:
    number: 2-46
    type: NC
  s_plunger:
    number: 2-37
  s_start:
    number: 0-7
    tags: start
  s_right_inlane:
    number: 2-15
    tags: playfield_active

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3



keyboard:
  z:
    switch: s_left_flipper
  '/':
    switch: s_right_flipper
  s:
    switch: s_start
  q:
    switch: s_right_inlane
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  4:
    switch: s_trough4
    toggle: true
  5:
    switch: s_trough5
    toggle: true
  p:
    switch: s_plunger
    toggle: true


coils:
  c_flipper_left_main:
    number: 2-35 #mid lug
    default_pulse_ms: 20
  c_flipper_left_hold:
    number: 2-36 #outer lug
    allow_enable: true
  c_flipper_right_main:
    number: 2-33 #mid lug
    default_pulse_ms: 20
  c_flipper_right_hold:
    number: 2-34 #outer lug
    allow_enable: true
  c_trough_eject:
    number: 2-39
    default_pulse_ms: 20
  c_plunger:
    number: 2-32
    default_pulse_ms: 20


playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper 
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    

displays:
  window:
    width: 1920
    height: 1080

slides:
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL!
        font_size: 50
        color: red
      - type: rectangle
        width: 240
        height: 60
  attract_started:
    widgets:
      - text: ATTRACT MODE
        type: text

slide_player:
  init_done: welcome_slide
  mode_attract_started: attract_started
  ball_started:
    widgets:
      type: text
      text: PLAYER (number) BALL (ball)

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    debug: true
  bd_plunger:
    ball_switches: s_plunger
    eject_coil: c_plunger
    mechanical_eject: true
    eject_timeouts: 3s
    



           