#config_version=5

hardware:


switches:
    s_left_flipper: 
        number: 4-38 #fifth board, switch 38
        tags: left_flipper
    s_left_flipper_eos:
        number: 0-3 #left flipper end of stroke switch first board, switch 3
        tags:  left_flipper_eos
    s_right_flipper: 
        number: 4-39 #fifth board, switch 39
        tags: right_flipper
    s_right_flipper_eos:
        number: 0-4 #right flipper end of stroke switch first board, switch 4
        tags: right_flipper_eos
    s_right_upper: 
        number: 5-40 #right upper flipper
        tags: right_upper
    s_right_upper_eos:
        number: 3-25 #right upper flipper end of stroke switch
    s_trough1:
        number: 5-44
        type: NC
    s_trough2:
        number: 5-45
        type: NC
    s_trough3:
        number: 5-46
        type: NC
    s_trough4:
        number: 5-47
        type: NC
    s_trough5:
        number: 6-48
        type: NC
    s_trough6:
        number: 6-49
        type: NC
    s_trough_jam:
        number: 7-56
        type: NC
    s_plunger:
        number: 0-5
    s_start:
        number: 5-41
        tags: start
    s_right_inlane:
        number: 1-8
        tags: playfield_active


   

coils:
    c_flipper_left_main: 
        number: 0-2 #first driver board, driver 2 
        default_pulse_ms: 20
    c_flipper_left_hold:
        number: 2-22
        allow_enable: true
    c_flipper_right_main: 
        number: 0-3
        default_pulse_ms: 20
    c_flipper_right_hold: 
        number: 2-23
        allow_enable: true
    c_right_upper_main: 
        number: 2-17
        default_pulse_ms: 20
    c_right_upper_hold: 
        number: 3-24
        allow_enable: true
    c_trough_eject:
        number: 0-0
        default_pulse_ms: 20
        

playfields: 
    playfield: 
        tags: default
        default_source_device: bd_plunger

flippers: 
    left_flipper:
        main_coil: c_flipper_left_main
        hold_coil: c_flipper_left_hold
        activation_switch: s_left_flipper
        eos_switch: s_left_flipper_eos
         
    right_flipper: 
        main_coil: c_flipper_right_main
        hold_coil: c_flipper_right_hold
        activation_switch: s_right_flipper
        eos_switch: s_right_flipper_eos
        
    right_upper:
        main_coil: c_right_upper_main
        hold_coil: c_right_upper_hold
        activation_switch: s_right_upper
        eos_switch:  s_right_upper_eos
        
    
displays:
    window:
        width: 800
        height: 600

slides:
    welcome_slide:
        widgets: 
            - type: text
              text: PINBALL!
              font_size: 50
              color: red
            - type: rectangle
              width: 240
              height: 60
    attract_started:
        widgets:
            - text: ATTRACT MODE
              type: text
slide_player:
    init_done: welcome_slide
    mode_attract_started: attract_started
    ball_started:
        widgets:
            type: text
            text: PLAYER (number) BALL (ball)


keyboard:
    z:
        switch: s_left_flipper
    m:
        switch: s_right_flipper
    s:
        switch: s_start
    q:
        switch: s_right_inlane
    1:
        switch: s_trough1
        toggle: true
    2:
        switch: s_trough2
        toggle: true
    3:
        switch: s_trough3
        toggle: true
    4:
        switch: s_trough4
        toggle: true
    5:
        switch: s_trough5
        toggle: true
    6:
        switch: s_trough6
        toggle: true
    p:
        switch: s_plunger
        toggle: true


ball_devices:
    bd_trough:
        ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
        eject_coil: c_trough_eject
        tags: trough, home, drain
        jam_switch: s_trough_jam
        eject_coil_jam_pulse: 15ms
        debug: true
    bd_plunger:
        ball_switches: s_plunger
        mechanical_eject: true
        eject_timeouts: 5s

virtual_platform_start_active_switches:
    - s_trough1
    - s_trough2
    - s_trough3
    - s_trough4
    - s_trough5
    - s_trough6




