#config_version=6

#Challenges_multiball

mode:
  start_events: start_challenges_multiball
  priority: 500
  stop_events: balls_in_play{balls==1}
  events_when_stopped: restart_mode_base


multiballs: 
  quick_add_2_ball:
    ball_count: 2
    ball_count_type: add
    shoot_again: 20s
    enable_events: mode_challenges_multiball_starting
    start_events:  mode_challenges_multiball_started

show_player:
  mode_challenges_multiball_started: 
    challenges_multiball_show:
      speed: 8
      loops: -1

sounds:
  jackpot:
    file: jackpot.wav
    track: voice
    volume: 0.9
    priority: 100
  multiball:
    file: multiball.wav
    track: voice
    volume: 0.9
    priority: 100
  another_jackpot:
    file: another_jackpot.wav
    track: voice
    volume: 0.9
    priority: 100
  first_ball_music:
    file: ball1_player1_5.wav
    track: music
    volume: 0.9
    priority: 100
  challenges_multiball:
    file: challenges_multiball.wav
    track: voice
    volume: 1.2
    priority: 500
   


sound_player:
  mode_challenges_multiball_started:
    challenges_multiball:
      action: play
      loops: 0

  slide_challenges_multi_finish_active:
    first_ball_music:
      action: play
  multiball_right_ramp_hit:
    jackpot:
      action: play
      block: true
  multiball_left_ramp_hit:
    jackpot:
      action: play
      block: true



slides:
  challenges_multiball:
    widgets:
      - type: text
        text: CHALLENGES MULTIBALL
        font_size: 150
        color: gold
      - type: image
        image: bar_screen
        scale: 1
  
  come_alive:
    widgets:
      - type: text
        text: CHALLENGES
        color: red
        font_size: 120
        y: 85%
      - type: text
        text: MULTIBALL
        color: red
        font_size: 120
        y: 15%

      - type: video
        video: come_alive
        volume: 0.3

  challenges_multi_finish:
    widgets:
      - type: text
        text: CHALLENGES MULTIBALL
        font_size: 150
        color: gold
      - type: image
        image: bar_screen
        scale: 1

slide_player:
  play_challenges_multiball_slide:
    challenges_multiball    
  play_come_alive_slide:
    come_alive
  remove_challenges_multiball_slide:
    challenges_multiball: 
      action: remove
  remove_come_alive_slide:
    come_alive:
      action: remove
  play_challenges_multi_finish_slide:
    challenges_multi_finish

event_player:
  mode_challenges_multiball_started:
    - play_challenges_multiball_slide
    - remove_challenges_multiball_slide|1s
    - play_come_alive_slide|1.1s
    - remove_come_alive_slide|61.5s
    - play_challenges_multi_finish_slide|61.6s
  balls_in_play{balls==1}:
    - stop_mode_challenges_multiball

  #slide_challenges_multi_finish_active:


videos:
  come_alive:
    file: come_alive.mpg




shots:
  multiball_left_ramp:
    switch: s_left_ramp_made
  multiball_right_ramp:
    switch: s_back_ramp_made

variable_player:
  multiball_left_ramp_hit:
    score: 1000000
  multiball_right_ramp_hit:
    score: 1000000


  