#config_version=6

#Challenges_multiball

mode:
  start_events: start_challenges_multiball
  priority: 500

multiballs: 
  quick_add_2_ball:
    ball_count: 2
    ball_count_type: add
    shoot_again: 20s
    enable_events: mode_challenges_multiball_starting
    start_events:  mode_challenges_multiball_started
  