#config_version=6

#Challenges_multiball

mode:
  start_events: start_challenges_multiball
  priority: 500

multiballs: 
  quick_add_2_ball:
    ball_count: 2
    ball_count_type: add
    shoot_again: 20s
    enable_events: mode_challenges_multiball_starting
    start_events:  mode_challenges_multiball_started

show_player:
  mode_challenges_multiball_started: 
    challenges_multiball_show:
      speed: 8
      loops: -1

sounds:
  jackpot:
    file: jackpot.wav
    track: voice
    volume: 0.9
    priority: 100
  multiball:
    file: multiball.wav
    track: voice
    volume: 0.9
    priority: 100
  another_jackpot:
    file: another_jackpot.wav
    track: voice
    volume: 0.9
    priority: 100



sound_player:
  mode_challenges_multiball_started:
    multiball:
      action: play
      loops: 0
  come_alive_slide_played:
    ball1_player1_5:
      action: stop
  slide_challenges_multi_finish_played:
    ball1_player1_5:
      action: play
slides:
  challenges_multiball:
    widgets:
      - type: text
        text: CHALLENGES MULTIBALL
        font_size: 150
        color: gold
      - type: image
        image: bar_screen
        scale: 1
  
  come_alive:
    type: video
    video: come_alive
    volume: 0.3

  challenges_multi_finish:
    widgets:
      - type: text
        text: CHALLENGES MULTIBALL
        font_size: 150
        color: gold
      - type: image
        image: bar_screen
        scale: 1

slide_player:
  play_challenges_multiball_slide:
    challenges_multiball    
  play_come_alive_slide:
    come_alive
  remove_challenges_multiball_slide:
    challenges_multiball: 
      action: remove
  remove_come_alive_slide:
    come_alive:
      action: remove
  play_challenges_multi_finish_slide:
    challenges_multi_finish

event_player:
  mode_challenges_multiball_started:
    - play_challenges_multiball_slide
    - remove_challenges_multiball_slide|2s
    - play_come_alive_slide|2.1s
    - remove_come_alive_slide|62s
    - play_challenges_multi_finish_slide|62.1s


videos:
  come_alive:
    file: come_alive.mpg




#shots:
  #skillshot_drop_1:
    #switch: 

  