#config_version=6

tilt:
  tilt_warning_switch_tag: tilt_warning
  warnings_to_tilt: 3
  multiple_hit_window: 3s
  settle_time: 5s

slide_player:
  _overwrite: true
  tilt_warning.2{warnings_remaining>1}:
    tilt_warning_1:
      expire: 4s
  

  tilt_warning.1{warnings_remaining==1}:
    tilt_warning_2:
      expire: 4s
  

  tilt:
    tilt:
      expire: 8s
    

  tilt_clear:
    tilt:
      action: remove




slides:
  _overwrite: true
  tilt_warning_1:
    widgets:
      - type: text
        text: WARNING!
        y: 81%
        font_size: 151
        color: black
      - type: text
        text: "Stop shaking the game"
        y: 41%
        font_size: 121
        color: black
      - type: image
        image: bar_screen

  tilt_warning_2:
    widgets:
      - type: text
        text: DANGER!
        y: 81%
        font_size: 151
        color: black
      - type: text
        text: "Be nice to this game"
        y: 41%
        font_size: 121
        color: black
      - type: image
        image: bar_screen

 
  tilt:
    widgets:
      - type: text
        text: TILT!
        y: 81%
        font_size: 151
        color: black
      - type: text
        text: "You were warned"
        y: 41%
        font_size: 121
        color: black
      - type: image
        image: bar_screen  

sound_player:
  tilt_warning.1{warnings_remaining>1}:
    tilt_1:
      volume: 1.5
  tilt_warning.2{warnings_remaining==1}:
    tilt_2:
      volume: 1.5
  tilt:
    tilt_3:
      volume: 1.5

sounds:
  tilt_1:
    file: tilt_firstwarning.wav
    track: sfx
    priority: 1000
  tilt_2:
    file: tilt_secondwarning.wav
    track: sfx
    priority: 1000
  tilt_3:
    file: tilt_finalbooing.wav
    track: sfx
    priority: 1000



    
 


