#config_version=6

tilt:
  tilt_switch_tag: tilt_warning
  warnings_to_tilt: 2
  multiple_hit_window: 3s
  settle_time: 5s




slides:
  _overwrite: true
  tilt_warning_1:
    widgets:
      - type: text
        text: WARNING!
        y: 81%
        font_size: 151
        color: black
      - type: text
        text: "Stop shaking the game."
        y: 41%
        font_size: 121
        color: black
      - type: image
        image: bar_screen
    expire: 2s
  tilt_warning_2:
    widgets:
      - type: text
        text: DANGER!
        y: 81%
        font_size: 151
        color: black
      - type: text
        text: "Be nice to this game."
        y: 41%
        font_size: 121
        color: black
      - type: image
        image: bar_screen
    expire: 2s
 
  tilt:
    widgets:
      - type: text
        text: TILT!
        y: 81%
        font_size: 151
        color: black
      - type: text
        text: "You were warned."
        y: 41%
        font_size: 121
        color: black
      - type: image
        image: bar_screen  
    expire: 2s  


    
 


