#config_version=6
mode:
  start_events: start_mode_greatest_showman_multiball
  priority: 10000
  stop_events: balls_in_play{balls==1}, stop_mode_greatest_showman_multiball
  events_when_stopped: restart_base_mode #start_mode_base2 

multiballs: 
  quick_add_5_ball:
    ball_count: 5
    ball_count_type: add
    shoot_again: 20s
    enable_events: mode_greatest_showman_multiball_starting
    start_events:  mode_greatest_showman_multiball_started

sounds:
  jackpot:
    file: jackpot.wav
    track: voice
    volume: 1.5
    priority: 1000
    block: true
  multiball:
    file: multiball.wav
    track: voice
    volume: 1.5
    priority: 100
  youve_collected_the_oddities:
    file: youve_collected_the_oddities.wav
    track: voice
    volume: 1.5
    priority: 1000
    block: true
  greatest_showman_mb:
    file: greatest_showman_mb.wav
    track: voice
    volume: 1.5
    priority: 6000
    block: true
  hit_everything:
    file: hit_everything.wav
    track: voice
    volume: 1.5
    priority: 6000
    block: true
  its_time_to_start_the_show:
    file: its_time_to_start_the_show.wav
    track: voice
    volume: 1.5
    priority: 1000
    block: true
  all_targets_10_times:
    file: all_targets_10_times.wav
    track: voice
    volume: 1.5
    priority: 6000
    block: true


sound_player:
    play_youve_collected_the_oddities:
      youve_collected_the_oddities:
        action: play
        priority: 1000 
    play_its_time_to_start_the_show:
      its_time_to_start_the_show:
        action: play
        priority: 1000 
    play_greatest_showman_mb:
      greatest_showman_mb:
        action: play
        priority: 1000 
    play_hit_everything:
      hit_everything:
        action: play
        priority: 1000 
    play_all_targets_10_times:
      all_targets_10_times:
        action: play
        priority: 1000 



slides:
  final_multiball:
    widgets:
      - type: text
        text: GREATEST SHOWMAN MULTIBALL
        color: red
        font_size: 110
        font_name: CarnivaleeFreakshow-DLrm
        y: 95%
      - type: text
        text: HIT EVERYTHING FOR 10X SCORING!
        color: gold
        font_size: 120
        font_name: CarnivaleeFreakshow-DLrm
        y: 83%
      - type: text
        text: (score)
        color: gold
        number_grouping: true
        min_digits: 2
        font_size: 160
        font_name: CarnivaleeFreakshow-DLrm
        y: 15% 
      - type: video
        video: final_multiball
        volume: 0.3 
  main_screen_tattooed_man:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        y: 22%
      - type: text
        text: PLAYER (number)
        y: 32%
        font_size: 50
      - type: text
        text: (ball)
        x: 18%
        y: 34.7%
        color: black
        font_size: 45
      - type: text
        text: 3
        x: 25.6%
        y: 34.7%
        color: black
        font_size: 45
      - type: text
        text: (orbit)
        x: 3.2%
        y: 72%
        font_size: 33
        color: black
      - type: text
        text: 4
        x: 7.95%
        y: 72%
        font_size: 33
        color: black
      - type: text
        text: (drops)
        x: 3%
        y: 56%
        font_size: 33
        color: black
      - type: text
        text: 10
        x: 7.8%
        y: 56%
        font_size: 33
        color: black    
      - type: text
        text: (ramps)
        x: 2.9%
        y: 41.7%
        font_size: 33
        color: black
      - type: text
        text: 4
        x: 7.55%
        y: 41.7%
        font_size: 33
        color: black  
      - type: text
        text: (tickets)
        x: 2.6%
        y: 25.7%
        font_size: 33
        color: black
      - type: text
        text: 8
        x: 7.5%
        y: 25.7%
        font_size: 33
        color: black  
      - type: text
        text: (pop)
        x: 2.6%
        y: 10%
        font_size: 33
        color: black
      - type: text
        text: 80
        x: 7.32%
        y: 10%
        font_size: 25
        color: black  
      - type: text
        text: (player1|score)
        x: 20%
        y: 9%
        color: white
        font_size: 60
        number_grouping: true
      - type: text
        text: (player2|score)
        x: 40%
        y: 9%
        color: white
        font_size: 60
        number_grouping: true
      - type: text
        text: (player3|score)
        x: 59%
        y: 9%
        color: white
        font_size: 60
        number_grouping: true
      - type: text
        text: (player4|score)
        x: 78%
        y: 9%
        color: white
        font_size: 60
        number_grouping: true
      - type: image
        image: main_screen_tattooed_man
        scale: 1


  


slide_player:
  play_final_multiball_slide:
    final_multiball    

  remove_final_multiball_slide:
    final_multiball: 
      action: remove

  play_main_screen_tattooed_man_slide:
    main_screen_tattooed_man
  remove_main_screen_tattooed_man_slide:
    main_screen_tattooed_man:
      action: remove

event_player:
  mode_greatest_showman_multiball_started:
    - play_youve_collected_the_oddities|6s
    - play_final_multiball_slide|8s
    - play_its_time_to_start_the_show|8.1s
    - play_greatest_showman_mb|9.5s
    - play_hit_everything| 12s
    - play_all_targets_10_times|17s




  balls_in_play{balls==1}:
    - stop_mode_greatest_showman_multiball
    - remove_final_multiball_slide
    - play_main_screen_tattooed_man_slide

shots:
#SPINNER
  gsmb_spinner:
    switch: s_spinner


#POP BUMPERS
  gsmb_top_pop_bumpers_top:
    switch: s_top_pop_bumpers_top

    tags: upper_pops
  gsmb_top_pop_bumpers_bottom:
    switch: s_top_pop_bumpers_bottom

    tags: upper_pops
  gsmb_top_pop_bumpers_left:
    switch: s_top_pop_bumpers_left

    tags: upper_pops
  gsmb_left_pop_bumpers_top:
    switch: s_left_pop_bumpers_top

  gsmb_left_pop_bumpers_right:
    switch: s_left_pop_bumpers_right

  gsmb_left_pop_bumpers_left:
    switch: s_left_pop_bumpers_left


#ORBITS
  gsmb_shot_left_orbit:
    enable_events: left_orbit_hit
  gsmb_shot_right_orbit:
    enable_events: right_orbit_hit
  gsmb_shot_inner_orbit: 
    enable_events: inner_orbit_hit

#DROP TARGETS

  gsmb_single_drop_target:
    switch: s_single_drop_target

  gsmb_front_drop_target:
    switch: s_3_bank_drop_target_1

  gsmb_middle_drop_target:
    switch: s_3_bank_drop_target_2

  gsmb_back_drop_target:
    switch: s_3_bank_drop_target_3

#TICKET BOOTHS

  gsmb_tickets:
    switch: s_left_ticket_booth

#RAMPS
  gsmb_left_ramp: #exit on left, but enter on right (lift ramp)
    switch: s_left_ramp_made

  gsmb_right_ramp:
    switch: s_back_ramp_made

#5 Million stand up
  gsmb_five_million_standup:
    switch: s_middle_stand_up_target

#STAND UPS
  gsmb_left_stand_up:
    switch: s_left_stand_up_target
  gsmb_middle_stand_up:
    switch: s_middle_stand_up_target
  gsmb_right_stand_up:
    switch: s_stand_up_target_right
  gsmb_stand_up_left_lift_ramp:
    switch: s_left_stand_up_target_lift_ramp
  gsmb_stand_up_right_lift_ramp:
    switch: s_right_stand_up_target_lift_ramp




variable_player:

#SPINNER
  gsmb_spinner_hit:
    score: 30000


#POP BUMPERS
  gsmb_top_pop_bumpers_top_hit:
    score: 80000

  gsmb_top_pop_bumpers_bottom_hit:
    score: 80000
  gsmb_top_pop_bumpers_left_hit:
    score: 80000
  gsmb_left_pop_bumpers_top_hit:
    score: 80000

  gsmb_left_pop_bumpers_right_hit:
    score: 80000

  gsmb_left_pop_bumpers_left_hit:
    score: 80000


#ORBITS
  gsmb_shot_left_orbit_hit:
    score: 800000
  gsmb_shot_right_orbit_hit:
    score: 800000
  gsmb_shot_inner_orbit_hit: 
    score: 800000

#DROP TARGETS

  gsmb_single_drop_target_hit:
    score: 1250000

  gsmb_front_drop_target_hit:
    score: 170000

  gsmb_middle_drop_target_hit:
    score: 170000

  gsmb_back_drop_target_hit:
    score: 170000

#TICKET BOOTHS

  gsmb_tickets_hit:
    score: 125000

#RAMPS
  gsmb_left_ramp_hit: 
    score:  800000

  gsmb_right_ramp_hit:
    score: 800000

#5 Million shot
  gsmb_five_million_standup_hit:
    score: 650000

#STAND UPS
  gsmb_left_stand_up_hit:
    score: 650000
  gsmb_middle_stand_up_hit:
    score: 650000
  gsmb_right_stand_up_hit:
    score: 650000
  gsmb_stand_up_left_lift_ramp_hit:
    score: 650000
  gsmb_stand_up_right_lift_ramp_hit:
    score: 650000




show_player:
  mode_greatest_showman_multiball_started: 
    greatest_showman_multiball_show:
      speed: 1
      loops: -1




track_player:
  mode_greatest_showman_multiball_started:
    music:
      action: stop_all_sounds
  mode_greatest_showman_multiball_will_stop:
    __all__:
      action: stop_all_sounds
      fade: 0.5s

videos:
  final_multiball:
    file: final_multiball.mpg
