#config_version=6
mode:
  start_events: start_mode_greatest_showman_multiball
  priority: 10000
  stop_events: balls_in_play{balls==1}
  events_when_stopped:  start_mode_base2 #restart_base_mode

multiballs: 
  quick_add_5_ball:
    ball_count: 5
    ball_count_type: add
    shoot_again: 20s
    enable_events: mode_greatest_showman_multiball_starting
    start_events:  mode_greatest_showman_multiball_started

sounds:
  jackpot:
    file: jackpot.wav
    track: voice
    volume: 0.9
    priority: 1000
    block: true
  multiball:
    file: multiball.wav
    track: voice
    volume: 0.9
    priority: 100
  youve_collected_the_oddities:
    file: youve_collected_the_oddities.wav
    track: voice
    volume: 0.9
    priority: 1000
    block: true
  greatest_showman_mb:
    file: greatest_showman_mb.wav
    track: voice
    volume: 0.9
    priority: 1000
    block: true
  hit_everything:
    file: hit_everything.wav
    track: voice
    volume: 0.9
    priority: 1000
    block: true
  its_time_to_start_the_show:
    file: its_time_to_start_the_show.wav
    track: voice
    volume: 0.9
    priority: 1000
    block: true
  all_targets_10_times:
    file: all_targets_10_times.wav
    track: voice
    volume: 0.9
    priority: 1000
    block: true


sound_player:
  mode_greatest_showman_multiball_started:
    youve_collected_the_oddities:
      action: play
      loops: 0
    its_time_to_start_the_show:
      action: play
      loops: 0
      delay: 2s
    greatest_showman_mb:
      action: play
      loops: 0
      delay: 5s
    hit_everything:
      action: play
      loops: 0
      delay: 10s
    all_targets_10_times:
      action: play
      loops: 0
      delay: 15s

slides:
  final_multiball:
    widgets:
      - type: text
        text: GREATEST SHOWMAN MULTIBALL
        color: red
        font_size: 110
        font_name: CarnivaleeFreakshow-DLrm
        y: 95%
      - type: text
        text: (score)
        color: gold
        number_grouping: true
        min_digits: 2
        font_size: 160
        font_name: CarnivaleeFreakshow-DLrm
        y: 15% 
      - type: video
        video: final_multiball
        volume: 0.3    


slide_player:
  play_final_multiball_slide:
    final_multiball    

  remove_final_multiball_slide:
    final_multiball: 
      action: remove

  #play_final_multi_finish_slide:
    #challenges_multi_finish

event_player:
  mode_greatest_showman_multiball_started:
    - play_final_multiball_slide
    #- remove_challenges_multiball_slide|1s
    #- play_come_alive_slide|1.1s
    #- remove_come_alive_slide|61.5s
    #- play_challenges_multi_finish_slide|61.6s
  balls_in_play{balls==0}:
    - stop_mode_greatest_showman_multiball

shots:
#SPINNER
  gsmb_spinner:
    switch: s_spinner


#POP BUMPERS
  gsmb_top_pop_bumpers_top:
    switch: s_top_pop_bumpers_top

    tags: upper_pops
  gsmb_top_pop_bumpers_bottom:
    switch: s_top_pop_bumpers_bottom

    tags: upper_pops
  gsmb_top_pop_bumpers_left:
    switch: s_top_pop_bumpers_left

    tags: upper_pops
  gsmb_left_pop_bumpers_top:
    switch: s_left_pop_bumpers_top

  gsmb_left_pop_bumpers_right:
    switch: s_left_pop_bumpers_right

  gsmb_left_pop_bumpers_left:
    switch: s_left_pop_bumpers_left


#ORBITS
  gsmb_shot_left_orbit:
    enable_events: left_orbit_hit
  gsmb_shot_right_orbit:
    enable_events: right_orbit_hit
  gsmb_shot_inner_orbit: 
    enable_events: inner_orbit_hit

#DROP TARGETS

  gsmb_single_drop_target:
    switch: s_single_drop_target

  gsmb_front_drop_target:
    switch: s_3_bank_drop_target_1

  gsmb_middle_drop_target:
    switch: s_3_bank_drop_target_2

  gsmb_back_drop_target:
    switch: s_3_bank_drop_target_3

#TICKET BOOTHS

  gsmb_tickets:
    switch: s_left_ticket_booth

#RAMPS
  gsmb_left_ramp: #exit on left, but enter on right (lift ramp)
    switch: s_left_ramp_made

  gsmb_right_ramp:
    switch: s_back_ramp_made

#5 Million stand up
  gsmb_five_million_standup:
    switch: s_middle_stand_up_target

#STAND UPS
  gsmb_left_stand_up:
    switch: s_left_stand_up_target
  gsmb_middle_stand_up:
    switch: s_middle_stand_up_target
  gsmb_right_stand_up:
    switch: s_stand_up_target_right
  gsmb_stand_up_left_lift_ramp:
    switch: s_left_stand_up_target_lift_ramp
  gsmb_stand_up_right_lift_ramp:
    switch: s_right_stand_up_target_lift_ramp




variable_player:

#SPINNER
  gsmb_spinner_hit:
    score: 30000


#POP BUMPERS
  gsmb_top_pop_bumpers_top_hit:
    score: 80000

  gsmb_top_pop_bumpers_bottom_hit:
    score: 80000
  gsmb_top_pop_bumpers_left_hit:
    score: 80000
  gsmb_left_pop_bumpers_top_hit:
    score: 80000

  gsmb_left_pop_bumpers_right_hit:
    score: 80000

  gsmb_left_pop_bumpers_left_hit:
    score: 80000


#ORBITS
  gsmb_shot_left_orbit_hit:
    score: 800000
  gsmb_shot_right_orbit_hit:
    score: 800000
  gsmb_shot_inner_orbit_hit: 
    score: 800000

#DROP TARGETS

  gsmb_single_drop_target_hit:
    score: 1250000

  gsmb_front_drop_target_hit:
    score: 170000

  gsmb_middle_drop_target_hit:
    score: 170000

  gsmb_back_drop_target_hit:
    score: 170000

#TICKET BOOTHS

  gsmb_tickets_hit:
    score: 125000

#RAMPS
  gsmb_left_ramp_hit: 
    score:  800000

  gsmb_right_ramp_hit:
    score: 800000

#5 Million shot
  gsmb_five_million_standup_hit:
    score: 650000

#STAND UPS
  gsmb_left_stand_up_hit:
    score: 650000
  gsmb_middle_stand_up_hit:
    score: 650000
  gsmb_right_stand_up_hit:
    score: 650000
  gsmb_stand_up_left_lift_ramp_hit:
    score: 650000
  gsmb_stand_up_right_lift_ramp_hit:
    score: 650000




show_player:
  mode_greatest_showman_multiball_started: 
    greatest_showman_multiball_show:
      speed: 1
      loops: -1




track_player:
  mode_greatest_showman_multiball_started:
    music:
      action: stop_all_sounds
  mode_greatest_showman_multiball_will_stop:
    __all__:
      action: stop_all_sounds
      fade: 0.5s

videos:
  final_multiball:
    file: final_multiball.mpg
