#config_version=6
mode:
  start_events: start_mode_lord_of_leeds
  stop_events: lord_of_leeds_complete, game_ending #ball_ended
  restart_on_next_ball: true
  events_when_stopped: start_mode_siamese_twins
  priority: 200




shots:
  right_orbit_lord_of_leeds: #F
    switch: s_right_orbit_bottom
    show_tokens: 
      lights: arrow_right_orbit
      color: purple
    profile: lord_of_leeds_profile
    advance_events: right_orbit_lord_of_leeds_flashing_hit
    control_events:
      - events: advance_lord_of_leeds_profile
        state: 2  
  right_ramp_lord_of_leeds: #H
    switch: s_back_ramp_made
    show_tokens:
      lights: lock, below_lock_in_musical_staff
      color: purple
    profile: lord_of_leeds_profile
    advance_events: right_ramp_lord_of_leeds_flashing_hit
    control_events:
      - events: advance_lord_of_leeds_profile
        state: 2  
  left_stand_up_lord_of_leeds: #C
    switch: s_left_stand_up_target
    show_tokens:
      lights: target_mid_left
      color: purple
    profile: lord_of_leeds_profile
    advance_events: left_stand_up_lord_of_leeds_flashing_hit
    control_events:
      - events: advance_lord_of_leeds_profile
        state: 2  

    



shot_profiles:
  lord_of_leeds_profile:
    states:
      - name: flashing
        show: purple_flashing
      - name: lit
        show: tom_thumb_lit
      - name: unlit
        show: off
    advance_on_hit: false



shows:
  purple_flashing:
    - duration: 200ms
      lights:
        (lights):
          color: yellow
    - duration: 200ms
      lights: 
        (lights): 
          color: black
  lord_of_leeds_lit:
    - duration: -1
      lights: 
       (lights):
         color: yellow 



counters:
  lord_of_leeds_counter:
    starting_count: 0
    count_events: right_orbit_lord_of_leeds_flashing_hit, right_ramp_lord_of_leeds_flashing_hit, left_stand_up_lord_of_leeds_flashing_hit
    count_complete_value: 3
    start_enabled: true
    persist_state: true
    reset_on_complete: false 
    events_when_complete: advance_lord_of_leeds_profile, light_oddities_5, lord_of_leeds_complete 
    #restart_events:  #five_million_standup_five_million_profile_lit_hit




variable_player:
  right_orbit_lord_of_leeds_flashing_hit:
    score: 500000
  right_ramp_lord_of_leeds_flashing_hit:
    score: 500000
  left_stand_up_lord_of_leeds_flashing_hit:
    score: 500000
  advance_lord_of_leeds_profile:
    score: 1000000





sounds:
  collect_8_oddities:
    file: collect_8_oddities.wav
    track: voice
    volume: 1.5
    priority: 1000
  shoot_the_colored_arrows:
    file: shoot_the_colored_arrows
    track: voice
    volume: 1.5
    priority: 1000

sound_player:
  mode_lord_of_leeds_started:
    collect_8_oddities:
      action: play
      track: voice
      loops: 0
      delay: 8s
    shoot_the_colored_arrows:
      action: play
      track: voice
      loops: 0
      delay: 10s









slides:
  main_screen_irish_giant:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        y: 22%
      - type: text
        text: PLAYER (number)
        y: 32%
        font_size: 50
      - type: text
        text: (ball)
        x: 18%
        y: 34.7%
        color: black
        font_size: 45
      - type: text
        text: 3
        x: 25.6%
        y: 34.7%
        color: black
        font_size: 45
      - type: text
        text: (orbit)
        x: 3.2%
        y: 72%
        font_size: 33
        color: black
      - type: text
        text: 4
        x: 7.95%
        y: 72%
        font_size: 33
        color: black
      - type: text
        text: (drops)
        x: 3%
        y: 56%
        font_size: 33
        color: black
      - type: text
        text: 10
        x: 7.8%
        y: 56%
        font_size: 33
        color: black    
      - type: text
        text: (ramps)
        x: 2.9%
        y: 41.7%
        font_size: 33
        color: black
      - type: text
        text: 4
        x: 7.55%
        y: 41.7%
        font_size: 33
        color: black  
      - type: text
        text: (tickets)
        x: 2.6%
        y: 25.7%
        font_size: 33
        color: black
      - type: text
        text: 8
        x: 7.5%
        y: 25.7%
        font_size: 33
        color: black  
      - type: text
        text: (pop)
        x: 2.6%
        y: 10%
        font_size: 33
        color: black
      - type: text
        text: 80
        x: 7.32%
        y: 10%
        font_size: 25
        color: black  
      - type: text
        text: (player1|score)
        x: 20%
        y: 9%
        color: white
        font_size: 60
        number_grouping: true
      - type: text
        text: (player2|score)
        x: 40%
        y: 9%
        color: white
        font_size: 60
        number_grouping: true
      - type: text
        text: (player3|score)
        x: 59%
        y: 9%
        color: white
        font_size: 60
        number_grouping: true
      - type: text
        text: (player4|score)
        x: 78%
        y: 9%
        color: white
        font_size: 60
        number_grouping: true
      - type: image
        image: main_screen_irish_giant
        scale: 1

      


slide_player:
  remove_main_screen_tom_thumb_slide:
    main_screen_tom_thumb:
      action: remove
  play_main_screen_irish_giant_slide:
    main_screen_irish_giant
  remove_main_screen_slide:
    main_screen:
      action: remove






event_player:
  mode_lord_of_leeds_started:
    - remove_main_screen_slide
    - remove_main_screen_tom_thumb_slide
    - play_main_screen_irish_giant_slide|7s

  restart_mode_lord_of_leeds:
    - remove_main_screen_slide
    - remove_main_screen_tom_thumb_slide
    - play_main_screen_irish_giant_slide


track_player:
  mode_lord_of_leeds_started:
    music:
      action: stop_all_sounds
  mode_lord_of_leeds_will_stop:
    __all__:
      action: stop_all_sounds
      fade: 1s

