#config_version=6
mode:
  start_events: start_mode_ramps
  stop_events: timer_ramps_timer_complete, ball_ended
  priority: 200

event_player:
  events_when_stopped: enable_qualify, start_mode_base


timers:
  ramps_timer:
    start_value: 20
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: mode_ramps_started
    start_running: false

show_player:
  mode_ramps_started: 
    ramps_show:
      speed: 1
    ramps_lights:
      speed: 10

track_player:
  mode_ramps_started:
    music:
      action: stop_all_sounds
  mode_ramps_will_stop:
    __all__:
      action: stop_all_sounds
      fade: 1s

sound_player:
  mode_ramps_started:
    ramps_challenge_completed:
      action: play
      track: voice
      loops: 0
    this_is_me:
      action: play
      track: music
      delay: 0.1s
      loops: 0
    shoot_ramps:
      action: play
      track: voice
      delay: 5s
      loops: 0  

  timer_ramps_timer_complete:
    this_is_me:
      action: stop
      fade_out: 1s




sounds:
  this_is_me:
    file: This_Is_Me.wav
    track: music
    volume: 0.6
    priority: 200
  ramps_challenge_completed:
    file: ramps_challenge_completed.wav
    track: voice
    volume: 1.5
    priority: 500
  shoot_ramps:
    file: shoot_the_ramps.wav
    track: voice
    volume: 1.5
    priority: 200


  

variable_player:
  left_ramp_ramps_hit:
    score: 800000
  right_ramp_ramps_hit:
    score: 800000
  timer_ramps_timer_tick:
    ramps_timer_seconds:
      int: device.timers.ramps_timer.ticks % 60
      action: set

shots:
  left_ramp_ramps:
    switch: s_left_ramp_made
  right_ramp_ramps:
    switch: s_back_ramp_made








    






  
  
  