#config_version=6

#this_is_me_multiball

mode:
  start_events: this_is_me_mb_counter_complete
  priority: 10000
  stop_events: balls_in_play{balls==1}
  events_when_stopped: restart_mode_base




multiballs:
  3balls_multiball:
    ball_count: 3
    ball_count_type: total
    shoot_again: 20s
    replace_balls_in_play: true
    start_events: mode_this_is_me_multiball_started

event_player:
  mode_this_is_me_multiball_started:
    - play_this_is_me_multiball_slide
    - remove_this_is_me_multiball_slide|1s
    - play_this_is_me_movie_slide|1.1s
    - eject_balls|4s
    - remove_this_is_me_movie_slide|93.1s
    - play_this_is_me_multi_finish_slide|93.2s
  balls_in_play{balls==1}:
    - stop_mode_this_is_me_multiball

track_player:
  mode_this_is_me_multiball_started:
    music:
      action: stop_all_sounds
  mode_this_is_me_multiball_will_stop:
    music: 
      action: stop_all_sounds

slides:
  this_is_me_multiball:
    widgets:
      - type: text
        text: THIS IS ME MULTIBALL
        font_size: 150
        color: gold
      - type: image
        image: bar_screen
        scale: 1
  
  this_is_me_movie:
    type: video
    video: this_is_me_movie
    volume: 0.6


  this_is_me_multi_finish:
    widgets:
      - type: text
        text: THIS IS ME MULTIBALL
        font_size: 150
        color: gold
      - type: image
        image: bar_screen
        scale: 1

slide_player:
  play_this_is_me_multiball_slide:
    this_is_me_multiball    
  play_this_is_me_movie_slide:
    this_is_me_movie
  remove_this_is_me_multiball_slide:
    this_is_me_multiball: 
      action: remove
  remove_this_is_me_movie_slide:
    this_is_me_movie:
      action: remove
  play_this_is_me_multi_finish_slide:
    this_is_me_multi_finish

videos:
  this_is_me_movie:
    file: this_is_me_movie.mpg


