#config_version=6

#this_is_me_multiball

mode:
  start_events: multiball_lock_ball_lock_full
  priority: 10000
  stop_events: balls_in_play{balls==1}
  events_when_stopped: restart_mode_base



multiballs:
  release_all_locked_balls:
    ball_count: 3
    ball_count_type: total
    shoot_again: 20s
    ball_locks: bd_ball_lock
    start_events: mode_this_is_me_multiball_started

event_player:
  mode_this_is_me_multiball_started:
    - play_this_is_me_multiball_slide
    - remove_this_is_me_multiball_slide|1s
    - play_come_alive_slide|1.1s
    - remove_come_alive_slide|61.5s
    - play_this_is_me_multi_finish_slide|61.6s
  balls_in_play{balls==1}:
    - stop_mode_this_is_me_multiball

track_player:
  mode_this_is_me_multiball_started:
    music:
      action: stop_all_sounds

slides:
  this_is_me_multiball:
    widgets:
      - type: text
        text: THIS IS ME MULTIBALL
        font_size: 150
        color: gold
      - type: image
        image: bar_screen
        scale: 1
  
  come_alive:
    widgets:
      - type: text
        text: THIS IS ME
        color: red
        font_size: 120
        y: 85%
      - type: text
        text: MULTIBALL
        color: red
        font_size: 120
        y: 15%

      - type: video
        video: come_alive
        volume: 0.3

  this_is_me_multi_finish:
    widgets:
      - type: text
        text: CHALLENGES MULTIBALL
        font_size: 150
        color: gold
      - type: image
        image: bar_screen
        scale: 1

slide_player:
  play_this_is_me_multiball_slide:
    this_is_me_multiball    
  play_come_alive_slide:
    come_alive
  remove_this_is_ms_multiball_slide:
    this_is_me_multiball: 
      action: remove
  remove_come_alive_slide:
    come_alive:
      action: remove
  play_this_is_me_multi_finish_slide:
    this_is_me_multi_finish


