#config_version=6

#this_is_me_multiball

mode:
  start_events: this_is_me_mb_counter_complete
  priority: 10000
  stop_events: stop_mode_this_is_me_multiball
  events_when_stopped: restart_mode_base




multiballs:
  this_is_me_multiball:
    ball_count: 2
    ball_count_type: add
    shoot_again: 20s
    enable_events: mode_this_is_me_multiball_started
    start_events: mode_this_is_me_multiball_started



event_player:
  mode_this_is_me_multiball_started:
    - play_this_is_me_multiball_slide
    - remove_this_is_me_multiball_slide|1s
    - play_this_is_me_movie_slide|1.1s
    - eject_balls|4s
    - remove_this_is_me_movie_slide|93.1s
    - play_this_is_me_multi_finish_slide|93.2s
  balls_in_play{balls==1}:
    - stop_mode_this_is_me_multiball

track_player:
  mode_this_is_me_multiball_started:
    music:
      action: stop_all_sounds
  mode_this_is_me_multiball_will_stop:
    __all__: 
      action: stop_all_sounds
      fade: 1s

slides:
  this_is_me_multiball:
    widgets:
      - type: text
        text: THIS IS ME MULTIBALL
        font_size: 150
        color: gold
        font_name: CarnivaleeFreakshow-DLrm
      - type: image
        image: bar_screen
        scale: 1
  
  this_is_me_movie:
    widgets:
      - type: text
        text: THIS IS ME MULTIBALL
        color: red
        font_name: CarnivaleeFreakshow-DLrm
        font_size: 120
        y: 95%
      - type: text
        text: SHOOT ORBITS FOR JACKPOT!
        color: gold
        font_size: 120
        font_name: CarnivaleeFreakshow-DLrm
        y: 83%
      - type: text
        text: (score)
        color: gold
        number_grouping: true
        min_digits: 2
        font_size: 140
        font_name: CarnivaleeFreakshow-DLrm
        y: 15%

      - type: video
        video: this_is_me_movie
        volume: 0.6


  this_is_me_multi_finish:
    widgets:
      - type: text
        text: THIS IS ME MULTIBALL
        font_size: 150
        color: gold
        font_name: CarnivaleeFreakshow-DLrm
        y: 75%
      - type: text
        text: (score)
        color: gold
        number_grouping: true
        min_digits: 2
        font_size: 140
        font_name: CarnivaleeFreakshow-DLrm
        y: 25%
      - type: image
        image: bar_screen
        scale: 1

slide_player:
  play_this_is_me_multiball_slide:
    this_is_me_multiball    
  play_this_is_me_movie_slide:
    this_is_me_movie
  remove_this_is_me_multiball_slide:
    this_is_me_multiball: 
      action: remove
  remove_this_is_me_movie_slide:
    this_is_me_movie:
      action: remove
  play_this_is_me_multi_finish_slide:
    this_is_me_multi_finish

videos:
  this_is_me_movie:
    file: this_is_me_movie.mpg



variable_player:
  multiball_left_orbit_hit:
    score: 1000000
  multiball_right_orbit_hit:
    score: 1000000
  multiball_inner_orbit_hit:
    score: 1000000

sequence_shots:
  multiball_left_orbit:
    switch_sequence: s_left_orbit_bottom, s_left_orbit_top, s_right_orbit_top
    sequence_timeout: 3s
  multiball_right_orbit:
    switch_sequence: s_right_orbit_bottom, s_right_orbit_top, s_left_orbit_top
    sequence_timeout: 3s
  multiball_inner_orbit:
    switch_sequence: s_inner_orbit_enter, s_right_orbit_top, s_right_orbit_bottom
    sequence_timeout: 3s

sounds:
  shoot_orbits:
    file: shoot_orbits.wav
    track: voice
    volume: 1.5
    priority: 1000
  jackpot:
    file: jackpot.wav
    track: voice
    volume: 0.9
    priority: 1000
    block: true

sound_player:
  mode_this_is_me_multiball_started:
    shoot_orbits:
      action: play
      loops: 0
      delay: 6s 
  multiball_left_orbit_hit:
    jackpot:
      action: play
      loops: 0
  multiball_right_orbit_hit:
    jackpot:
      action: play
      loops: 0
  multiball_inner_orbit_hit:
    jackpot:
      action: play
      loops: 0

show_player:
  mode_this_is_me_multiball_started: 
    this_is_me_lights:
      speed: 10
      loops: -1

