#config_version=6
mode:
  start_events: start_mode_tickets
  stop_events: timer_tickets_timer_complete
  priority: 200

event_player:
  events_when_complete: enable_qualify



timers:
  tickets_timer:
    start_value: 20
    end_value: 0
    direction: down
    tick_interval: 1s
    control_events:
      - action: start
        event: mode_tickets_started
    start_running: false

show_player:
  mode_tickets_started: 
    tickets_show:
      speed: 1
    tickets_lights:
      speed: 10


sound_player:
  mode_tickets_started:
    tickets_challenge_completed:
      action: play
      loops: 0
    come_alive:
      action: play
      track: music
      loops: 0
    shoot_tickets:
      action: play
      track: voice
      delay: 5s
      loops: 0
  timer_tickets_timer_complete:
    come_alive:
      action: stop
      fade_out: 1s

sounds:
  tickets_challenge_completed:
    file: sell_tickets_complete.wav
    track: voice
    volume: 1.5
    priority: 200
  come_alive:
    file: Come_Alive.wav
    track: music
    volume: 0.2
    priority: 200
  shoot_tickets:
    file: shoot_tickets.wav
    track: voice
    volume: 1.5
    priority: 200

variable_player:
  tickets_tickets_hit:
    score: 1000
  timer_tickets_timer_tick:
    tickets_timer_seconds:
      int: device.timers.tickets_timer.ticks % 60
      action: set

shots:
  tickets_tickets:
    switch: s_left_ticket_booth





    






  
  
  