#config_version=6
mode:
  start_events: start_mode_tattooed_man
  stop_events: tattooed_man_complete, game_ending #ball_ended
  restart_on_next_ball: true
  events_when_stopped: start_mode_greatest_showman_multiball
  priority: 200




shots:
  left_orbit_tattooed_man:  #B
    switch: s_left_orbit_bottom
    show_tokens:
      lights: arrow_outer_left_orbit
      color: orange
    profile: tattooed_man_profile
    advance_events: left_orbit_tattooed_man_flashing_hit
    control_events:
      - events: advance_tattooed_man_profile
        state: 2
  right_ramp_tattooed_man: #H
    switch: s_left_ramp_made
    show_tokens:
      lights: below_lock_in_musical_staff
      color: orange
    profile: tattooed_man_profile
    advance_events: right_ramp_tattooed_man_flashing_hit
    control_events:
      - events: advance_tattooed_man_profile
        state: 2  
  left_ramp_tattooed_man: #I
    switch: s_back_ramp_made
    show_tokens:
      lights: miss, jenny, lind
      color: orange
    profile: tattooed_man_profile
    advance_events: left_ramp_tattooed_man_flashing_hit
    control_events:
      - events: advance_tattooed_man_profile
        state: 2  




 

shot_profiles:
  tattooed_man_profile:
    states:
      - name: flashing
        show: orange_flashing
      - name: lit
        show: tattooed_man_lit
      - name: unlit
        show: off
    advance_on_hit: false



shows:
  orange_flashing:
    - duration: 200ms
      lights:
        (lights):
          color: orange
    - duration: 200ms
      lights: 
        (lights): 
          color: black
  tattooed_man_lit:
    - duration: -1
      lights: 
       (lights):
         color: orange 



counters:
  tattooed_man_counter:
    starting_count: 0
    count_events: left_orbit_tattooed_man_flashing_hit, right_ramp_tattooed_man_flashing_hit, left_ramp_tattooed_man_flashing_hit
    count_complete_value: 3
    start_enabled: true
    persist_state: true
    reset_on_complete: false 
    events_when_complete: advance_tattooed_man_profile, light_oddities_8, tattooed_man_complete 
    #restart_events:  #five_million_standup_five_million_profile_lit_hit




variable_player:
  left_orbit_tattooed_man_flashing_hit:
    score: 500000
  right_ramp_tattooed_man_flashing_hit:
    score: 500000
  left_ramp_tattooed_man_flashing_hit:
    score: 500000
  advance_tattooed_man_profile:
    score: 1000000





sounds:
  collect_8_oddities:
    file: collect_8_oddities.wav
    track: voice
    volume: 1.5
    priority: 1000
  shoot_the_colored_arrows:
    file: shoot_the_colored_arrows
    track: voice
    volume: 1.5
    priority: 1000
  rewrite_the_stars:
    file: rewrite_the_stars.wav
    track: music
    volume: 0.5
    priority: 900

sound_player:
  play_collect_8_oddities:
    collect_8_oddities:
      action: play
      priority: 1000
  play_shoot_the_colored_arrows:
    shoot_the_colored_arrows:
      action: play
      priority: 1000
  play_rewrite_the_stars:
    rewrite_the_stars:
      action: play
      priority: 1000  










slides:
  main_screen_trapeze_artist:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
        y: 22%
      - type: text
        text: PLAYER (number)
        y: 32%
        font_size: 50
      - type: text
        text: (ball)
        x: 18%
        y: 34.7%
        color: black
        font_size: 45
      - type: text
        text: 3
        x: 25.6%
        y: 34.7%
        color: black
        font_size: 45
      - type: text
        text: (orbit)
        x: 3.2%
        y: 72%
        font_size: 33
        color: black
      - type: text
        text: 4
        x: 7.95%
        y: 72%
        font_size: 33
        color: black
      - type: text
        text: (drops)
        x: 3%
        y: 56%
        font_size: 33
        color: black
      - type: text
        text: 10
        x: 7.8%
        y: 56%
        font_size: 33
        color: black    
      - type: text
        text: (ramps)
        x: 2.9%
        y: 41.7%
        font_size: 33
        color: black
      - type: text
        text: 4
        x: 7.55%
        y: 41.7%
        font_size: 33
        color: black  
      - type: text
        text: (tickets)
        x: 2.6%
        y: 25.7%
        font_size: 33
        color: black
      - type: text
        text: 8
        x: 7.5%
        y: 25.7%
        font_size: 33
        color: black  
      - type: text
        text: (pop)
        x: 2.6%
        y: 10%
        font_size: 33
        color: black
      - type: text
        text: 80
        x: 7.32%
        y: 10%
        font_size: 25
        color: black  
      - type: text
        text: (player1|score)
        x: 20%
        y: 9%
        color: white
        font_size: 60
        number_grouping: true
      - type: text
        text: (player2|score)
        x: 40%
        y: 9%
        color: white
        font_size: 60
        number_grouping: true
      - type: text
        text: (player3|score)
        x: 59%
        y: 9%
        color: white
        font_size: 60
        number_grouping: true
      - type: text
        text: (player4|score)
        x: 78%
        y: 9%
        color: white
        font_size: 60
        number_grouping: true
      - type: image
        image: main_screen_trapeze_artist
        scale: 1

      


slide_player:
  remove_main_screen_siamese_twins_slide:
    main_screen_siamese_twins:
      action: remove
  play_main_screen_trapeze_artist_slide:
    main_screen_trapeze_artist
  remove_main_screen_slide:
    main_screen:
      action: remove






event_player:
  mode_tattooed_man_started:
    - remove_main_screen_slide
    - remove_main_screen_siamese_twins_slide
    - play_main_screen_trapeze_artist_slide|7s
    - play_collect_8_oddities|7.2s
    - play_shoot_the_colored_arrows|10.2s
    - play_rewrite_the_stars|12.2s

  restart_mode_tattooed_man:
    - remove_main_screen_slide
    - remove_main_screen_siamese_twins_slide
    - play_main_screen_trapeze_artist_slide


track_player:
  mode_tattooed_man_started:
    music:
      action: stop_all_sounds
  mode_tattooed_man_will_stop:
    __all__:
      action: stop_all_sounds
      fade: 1s

